/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body2
 */
export interface Body2 {
    /**
     * 
     * @type {string}
     * @memberof Body2
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof Body2
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof Body2
     */
    seconds?: any;
    /**
     * 
     * @type {Date}
     * @memberof Body2
     */
    startDate?: any;
    /**
     * 
     * @type {Date}
     * @memberof Body2
     */
    endDate?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Body2
     */
    shear?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Body2
     */
    center?: any;
}
