/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    unisCustomerCd?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    customerName?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    customerGroupCd?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    customerGroupName?: any;
}
