name: umesse
description: umesse demo

version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  path_provider: ^1.6.10
  permission_handler: ^5.0.0+hotfix.9
  assets_audio_player: ^2.0.1
  soundpool: ^1.1.1
  flutter_sound: ^5.0.1
  flutter_tts: ^1.2.2
  flutter_ffmpeg: ^0.2.10
  audioplayer: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/presetvoices.json
