@startuml u-messe version alpha

left to right direction
actor user
file cm
rectangle "CM作成アプリ" {
  usecase "音源作成(音声録音・TTS)" as u1
  usecase "音源組立" as u2
  usecase "音源出力" as u3
  usecase "収録音源" as u4
}
rectangle "外部デバイス" {
  usecase "再生" as d1
}

title ** 音源作成・出力 **
user ---> u1
user ---> u2
user ---> u3
u1 .> u2
u4 .> u2
u3 --> cm
u3 --> d1

@enduml