import converter from "@/utils/converter";

describe("timeのテスト", () => {
  const datas = [
    { timeString: "0:00", lang: "ja", expected: "午前0時" },
    { timeString: "0:10", lang: "ja", expected: "午前0時10分" },
    { timeString: "1:00", lang: "ja", expected: "午前1時" },
    { timeString: "2:00", lang: "ja", expected: "午前2時" },
    { timeString: "3:00", lang: "ja", expected: "午前3時" },
    { timeString: "4:00", lang: "ja", expected: "午前4時" },
    { timeString: "5:00", lang: "ja", expected: "午前5時" },
    { timeString: "6:00", lang: "ja", expected: "午前6時" },
    { timeString: "7:00", lang: "ja", expected: "午前7時" },
    { timeString: "8:00", lang: "ja", expected: "午前8時" },
    { timeString: "9:00", lang: "ja", expected: "午前9時" },
    { timeString: "00:00", lang: "ja", expected: "午前0時" },
    { timeString: "00:10", lang: "ja", expected: "午前0時10分" },
    { timeString: "01:00", lang: "ja", expected: "午前1時" },
    { timeString: "02:00", lang: "ja", expected: "午前2時" },
    { timeString: "03:00", lang: "ja", expected: "午前3時" },
    { timeString: "04:00", lang: "ja", expected: "午前4時" },
    { timeString: "05:00", lang: "ja", expected: "午前5時" },
    { timeString: "06:00", lang: "ja", expected: "午前6時" },
    { timeString: "07:00", lang: "ja", expected: "午前7時" },
    { timeString: "08:00", lang: "ja", expected: "午前8時" },
    { timeString: "09:00", lang: "ja", expected: "午前9時" },
    { timeString: "10:00", lang: "ja", expected: "午前10時" },
    { timeString: "11:00", lang: "ja", expected: "午前11時" },
    { timeString: "12:00", lang: "ja", expected: "午後0時" },
    { timeString: "13:00", lang: "ja", expected: "午後1時" },
    { timeString: "14:00", lang: "ja", expected: "午後2時" },
    { timeString: "15:00", lang: "ja", expected: "午後3時" },
    { timeString: "16:00", lang: "ja", expected: "午後4時" },
    { timeString: "17:00", lang: "ja", expected: "午後5時" },
    { timeString: "18:00", lang: "ja", expected: "午後6時" },
    { timeString: "19:00", lang: "ja", expected: "午後7時" },
    { timeString: "20:00", lang: "ja", expected: "午後8時" },
    { timeString: "21:00", lang: "ja", expected: "午後9時" },
    { timeString: "22:00", lang: "ja", expected: "午後10時" },
    { timeString: "23:00", lang: "ja", expected: "午後11時" },
    { timeString: "0:00", lang: "en", expected: "12:00 a.m" },
    { timeString: "0:10", lang: "en", expected: "12:10 a.m" },
    { timeString: "1:00", lang: "en", expected: "1:00 a.m" },
    { timeString: "2:00", lang: "en", expected: "2:00 a.m" },
    { timeString: "3:00", lang: "en", expected: "3:00 a.m" },
    { timeString: "4:00", lang: "en", expected: "4:00 a.m" },
    { timeString: "5:00", lang: "en", expected: "5:00 a.m" },
    { timeString: "6:00", lang: "en", expected: "6:00 a.m" },
    { timeString: "7:00", lang: "en", expected: "7:00 a.m" },
    { timeString: "8:00", lang: "en", expected: "8:00 a.m" },
    { timeString: "9:00", lang: "en", expected: "9:00 a.m" },
    { timeString: "00:00", lang: "en", expected: "12:00 a.m" },
    { timeString: "00:10", lang: "en", expected: "12:10 a.m" },
    { timeString: "01:00", lang: "en", expected: "1:00 a.m" },
    { timeString: "02:00", lang: "en", expected: "2:00 a.m" },
    { timeString: "03:00", lang: "en", expected: "3:00 a.m" },
    { timeString: "04:00", lang: "en", expected: "4:00 a.m" },
    { timeString: "05:00", lang: "en", expected: "5:00 a.m" },
    { timeString: "06:00", lang: "en", expected: "6:00 a.m" },
    { timeString: "07:00", lang: "en", expected: "7:00 a.m" },
    { timeString: "08:00", lang: "en", expected: "8:00 a.m" },
    { timeString: "09:00", lang: "en", expected: "9:00 a.m" },
    { timeString: "10:00", lang: "en", expected: "10:00 a.m" },
    { timeString: "11:00", lang: "en", expected: "11:00 a.m" },
    { timeString: "12:00", lang: "en", expected: "12:00 p.m" },
    { timeString: "13:00", lang: "en", expected: "1:00 p.m" },
    { timeString: "14:00", lang: "en", expected: "2:00 p.m" },
    { timeString: "15:00", lang: "en", expected: "3:00 p.m" },
    { timeString: "16:00", lang: "en", expected: "4:00 p.m" },
    { timeString: "17:00", lang: "en", expected: "5:00 p.m" },
    { timeString: "18:00", lang: "en", expected: "6:00 p.m" },
    { timeString: "19:00", lang: "en", expected: "7:00 p.m" },
    { timeString: "20:00", lang: "en", expected: "8:00 p.m" },
    { timeString: "21:00", lang: "en", expected: "9:00 p.m" },
    { timeString: "22:00", lang: "en", expected: "10:00 p.m" },
    { timeString: "23:00", lang: "en", expected: "11:00 p.m" },
    { timeString: "0:00", lang: "zh", expected: "凌晨12点" },
    { timeString: "0:10", lang: "zh", expected: "凌晨12点10分" },
    { timeString: "1:00", lang: "zh", expected: "凌晨1点" },
    { timeString: "2:00", lang: "zh", expected: "凌晨2点" },
    { timeString: "3:00", lang: "zh", expected: "凌晨3点" },
    { timeString: "4:00", lang: "zh", expected: "凌晨4点" },
    { timeString: "5:00", lang: "zh", expected: "早上5点" },
    { timeString: "6:00", lang: "zh", expected: "早上6点" },
    { timeString: "7:00", lang: "zh", expected: "早上7点" },
    { timeString: "8:00", lang: "zh", expected: "早上8点" },
    { timeString: "9:00", lang: "zh", expected: "上午9点" },
    { timeString: "00:00", lang: "zh", expected: "凌晨12点" },
    { timeString: "00:10", lang: "zh", expected: "凌晨12点10分" },
    { timeString: "01:00", lang: "zh", expected: "凌晨1点" },
    { timeString: "02:00", lang: "zh", expected: "凌晨2点" },
    { timeString: "03:00", lang: "zh", expected: "凌晨3点" },
    { timeString: "04:00", lang: "zh", expected: "凌晨4点" },
    { timeString: "05:00", lang: "zh", expected: "早上5点" },
    { timeString: "06:00", lang: "zh", expected: "早上6点" },
    { timeString: "07:00", lang: "zh", expected: "早上7点" },
    { timeString: "08:00", lang: "zh", expected: "早上8点" },
    { timeString: "09:00", lang: "zh", expected: "上午9点" },
    { timeString: "10:00", lang: "zh", expected: "上午10点" },
    { timeString: "11:00", lang: "zh", expected: "上午11点" },
    { timeString: "12:00", lang: "zh", expected: "中午12点" },
    { timeString: "13:00", lang: "zh", expected: "下午1点" },
    { timeString: "14:00", lang: "zh", expected: "下午2点" },
    { timeString: "15:00", lang: "zh", expected: "下午3点" },
    { timeString: "16:00", lang: "zh", expected: "下午4点" },
    { timeString: "17:00", lang: "zh", expected: "下午5点" },
    { timeString: "18:00", lang: "zh", expected: "晚上6点" },
    { timeString: "19:00", lang: "zh", expected: "晚上7点" },
    { timeString: "20:00", lang: "zh", expected: "晚上8点" },
    { timeString: "21:00", lang: "zh", expected: "晚上9点" },
    { timeString: "22:00", lang: "zh", expected: "晚上10点" },
    { timeString: "23:00", lang: "zh", expected: "晚上11点" },
    { timeString: "0:00", lang: "ko", expected: "자정" },
    { timeString: "0:10", lang: "ko", expected: "오전 0시 10 분" },
    { timeString: "1:00", lang: "ko", expected: "오전 1시" },
    { timeString: "2:00", lang: "ko", expected: "오전 2시" },
    { timeString: "3:00", lang: "ko", expected: "오전 3시" },
    { timeString: "4:00", lang: "ko", expected: "오전 4시" },
    { timeString: "5:00", lang: "ko", expected: "오전 5시" },
    { timeString: "6:00", lang: "ko", expected: "오전 6시" },
    { timeString: "7:00", lang: "ko", expected: "오전 7시" },
    { timeString: "8:00", lang: "ko", expected: "오전 8시" },
    { timeString: "9:00", lang: "ko", expected: "오전 9시" },
    { timeString: "00:00", lang: "ko", expected: "자정" },
    { timeString: "00:10", lang: "ko", expected: "오전 0시 10 분" },
    { timeString: "01:00", lang: "ko", expected: "오전 1시" },
    { timeString: "02:00", lang: "ko", expected: "오전 2시" },
    { timeString: "03:00", lang: "ko", expected: "오전 3시" },
    { timeString: "04:00", lang: "ko", expected: "오전 4시" },
    { timeString: "05:00", lang: "ko", expected: "오전 5시" },
    { timeString: "06:00", lang: "ko", expected: "오전 6시" },
    { timeString: "07:00", lang: "ko", expected: "오전 7시" },
    { timeString: "08:00", lang: "ko", expected: "오전 8시" },
    { timeString: "09:00", lang: "ko", expected: "오전 9시" },
    { timeString: "10:00", lang: "ko", expected: "오전 10시" },
    { timeString: "11:00", lang: "ko", expected: "오전 11시" },
    { timeString: "12:00", lang: "ko", expected: "오후 12시" },
    { timeString: "13:00", lang: "ko", expected: "오후 1시" },
    { timeString: "14:00", lang: "ko", expected: "오후 2시" },
    { timeString: "15:00", lang: "ko", expected: "오후 3시" },
    { timeString: "16:00", lang: "ko", expected: "오후 4시" },
    { timeString: "17:00", lang: "ko", expected: "오후 5시" },
    { timeString: "18:00", lang: "ko", expected: "오후 6시" },
    { timeString: "19:00", lang: "ko", expected: "오후 7시" },
    { timeString: "20:00", lang: "ko", expected: "오후 8시" },
    { timeString: "21:00", lang: "ko", expected: "오후 9시" },
    { timeString: "22:00", lang: "ko", expected: "오후 10시" },
    { timeString: "23:00", lang: "ko", expected: "오후 11시" },
    { timeString: "0:00", lang: "aa", expected: "" },
  ];
  datas.forEach((v) => {
    test(`引数に("${v.timeString}", "${v.lang}")を渡すと"${v.expected}"が返ること`, () => {
      expect(converter.time(v.timeString, v.lang)).toBe(v.expected);
    });
  });
});
