import ttsTextConverter from "@/utils/ttsTextConverter";

describe("convertTimeのテスト", () => {
  const datas = [
    { timeString: "0:00", lang: "ja", expected: "午前0時" },
    { timeString: "0:10", lang: "ja", expected: "午前0時10分" },
    { timeString: "1:00", lang: "ja", expected: "午前1時" },
    { timeString: "2:00", lang: "ja", expected: "午前2時" },
    { timeString: "3:00", lang: "ja", expected: "午前3時" },
    { timeString: "4:00", lang: "ja", expected: "午前4時" },
    { timeString: "5:00", lang: "ja", expected: "午前5時" },
    { timeString: "6:00", lang: "ja", expected: "午前6時" },
    { timeString: "7:00", lang: "ja", expected: "午前7時" },
    { timeString: "8:00", lang: "ja", expected: "午前8時" },
    { timeString: "9:00", lang: "ja", expected: "午前9時" },
    { timeString: "00:00", lang: "ja", expected: "午前0時" },
    { timeString: "00:10", lang: "ja", expected: "午前0時10分" },
    { timeString: "01:00", lang: "ja", expected: "午前1時" },
    { timeString: "02:00", lang: "ja", expected: "午前2時" },
    { timeString: "03:00", lang: "ja", expected: "午前3時" },
    { timeString: "04:00", lang: "ja", expected: "午前4時" },
    { timeString: "05:00", lang: "ja", expected: "午前5時" },
    { timeString: "06:00", lang: "ja", expected: "午前6時" },
    { timeString: "07:00", lang: "ja", expected: "午前7時" },
    { timeString: "08:00", lang: "ja", expected: "午前8時" },
    { timeString: "09:00", lang: "ja", expected: "午前9時" },
    { timeString: "10:00", lang: "ja", expected: "午前10時" },
    { timeString: "11:00", lang: "ja", expected: "午前11時" },
    { timeString: "12:00", lang: "ja", expected: "午後0時" },
    { timeString: "13:00", lang: "ja", expected: "午後1時" },
    { timeString: "14:00", lang: "ja", expected: "午後2時" },
    { timeString: "15:00", lang: "ja", expected: "午後3時" },
    { timeString: "16:00", lang: "ja", expected: "午後4時" },
    { timeString: "17:00", lang: "ja", expected: "午後5時" },
    { timeString: "18:00", lang: "ja", expected: "午後6時" },
    { timeString: "19:00", lang: "ja", expected: "午後7時" },
    { timeString: "20:00", lang: "ja", expected: "午後8時" },
    { timeString: "21:00", lang: "ja", expected: "午後9時" },
    { timeString: "22:00", lang: "ja", expected: "午後10時" },
    { timeString: "23:00", lang: "ja", expected: "午後11時" },
    { timeString: "0:00", lang: "en", expected: "12:00 a.m" },
    { timeString: "0:10", lang: "en", expected: "12:10 a.m" },
    { timeString: "1:00", lang: "en", expected: "1:00 a.m" },
    { timeString: "2:00", lang: "en", expected: "2:00 a.m" },
    { timeString: "3:00", lang: "en", expected: "3:00 a.m" },
    { timeString: "4:00", lang: "en", expected: "4:00 a.m" },
    { timeString: "5:00", lang: "en", expected: "5:00 a.m" },
    { timeString: "6:00", lang: "en", expected: "6:00 a.m" },
    { timeString: "7:00", lang: "en", expected: "7:00 a.m" },
    { timeString: "8:00", lang: "en", expected: "8:00 a.m" },
    { timeString: "9:00", lang: "en", expected: "9:00 a.m" },
    { timeString: "00:00", lang: "en", expected: "12:00 a.m" },
    { timeString: "00:10", lang: "en", expected: "12:10 a.m" },
    { timeString: "01:00", lang: "en", expected: "1:00 a.m" },
    { timeString: "02:00", lang: "en", expected: "2:00 a.m" },
    { timeString: "03:00", lang: "en", expected: "3:00 a.m" },
    { timeString: "04:00", lang: "en", expected: "4:00 a.m" },
    { timeString: "05:00", lang: "en", expected: "5:00 a.m" },
    { timeString: "06:00", lang: "en", expected: "6:00 a.m" },
    { timeString: "07:00", lang: "en", expected: "7:00 a.m" },
    { timeString: "08:00", lang: "en", expected: "8:00 a.m" },
    { timeString: "09:00", lang: "en", expected: "9:00 a.m" },
    { timeString: "10:00", lang: "en", expected: "10:00 a.m" },
    { timeString: "11:00", lang: "en", expected: "11:00 a.m" },
    { timeString: "12:00", lang: "en", expected: "12:00 p.m" },
    { timeString: "13:00", lang: "en", expected: "1:00 p.m" },
    { timeString: "14:00", lang: "en", expected: "2:00 p.m" },
    { timeString: "15:00", lang: "en", expected: "3:00 p.m" },
    { timeString: "16:00", lang: "en", expected: "4:00 p.m" },
    { timeString: "17:00", lang: "en", expected: "5:00 p.m" },
    { timeString: "18:00", lang: "en", expected: "6:00 p.m" },
    { timeString: "19:00", lang: "en", expected: "7:00 p.m" },
    { timeString: "20:00", lang: "en", expected: "8:00 p.m" },
    { timeString: "21:00", lang: "en", expected: "9:00 p.m" },
    { timeString: "22:00", lang: "en", expected: "10:00 p.m" },
    { timeString: "23:00", lang: "en", expected: "11:00 p.m" },
    { timeString: "0:00", lang: "zh", expected: "凌晨12点" },
    { timeString: "0:10", lang: "zh", expected: "凌晨12点10分" },
    { timeString: "1:00", lang: "zh", expected: "凌晨1点" },
    { timeString: "2:00", lang: "zh", expected: "凌晨2点" },
    { timeString: "3:00", lang: "zh", expected: "凌晨3点" },
    { timeString: "4:00", lang: "zh", expected: "凌晨4点" },
    { timeString: "5:00", lang: "zh", expected: "早上5点" },
    { timeString: "6:00", lang: "zh", expected: "早上6点" },
    { timeString: "7:00", lang: "zh", expected: "早上7点" },
    { timeString: "8:00", lang: "zh", expected: "早上8点" },
    { timeString: "9:00", lang: "zh", expected: "上午9点" },
    { timeString: "00:00", lang: "zh", expected: "凌晨12点" },
    { timeString: "00:10", lang: "zh", expected: "凌晨12点10分" },
    { timeString: "01:00", lang: "zh", expected: "凌晨1点" },
    { timeString: "02:00", lang: "zh", expected: "凌晨2点" },
    { timeString: "03:00", lang: "zh", expected: "凌晨3点" },
    { timeString: "04:00", lang: "zh", expected: "凌晨4点" },
    { timeString: "05:00", lang: "zh", expected: "早上5点" },
    { timeString: "06:00", lang: "zh", expected: "早上6点" },
    { timeString: "07:00", lang: "zh", expected: "早上7点" },
    { timeString: "08:00", lang: "zh", expected: "早上8点" },
    { timeString: "09:00", lang: "zh", expected: "上午9点" },
    { timeString: "10:00", lang: "zh", expected: "上午10点" },
    { timeString: "11:00", lang: "zh", expected: "上午11点" },
    { timeString: "12:00", lang: "zh", expected: "中午12点" },
    { timeString: "13:00", lang: "zh", expected: "下午1点" },
    { timeString: "14:00", lang: "zh", expected: "下午2点" },
    { timeString: "15:00", lang: "zh", expected: "下午3点" },
    { timeString: "16:00", lang: "zh", expected: "下午4点" },
    { timeString: "17:00", lang: "zh", expected: "下午5点" },
    { timeString: "18:00", lang: "zh", expected: "晚上6点" },
    { timeString: "19:00", lang: "zh", expected: "晚上7点" },
    { timeString: "20:00", lang: "zh", expected: "晚上8点" },
    { timeString: "21:00", lang: "zh", expected: "晚上9点" },
    { timeString: "22:00", lang: "zh", expected: "晚上10点" },
    { timeString: "23:00", lang: "zh", expected: "晚上11点" },
    { timeString: "0:00", lang: "ko", expected: "자정" },
    { timeString: "0:10", lang: "ko", expected: "오전 0시 10 분" },
    { timeString: "1:00", lang: "ko", expected: "오전 1시" },
    { timeString: "2:00", lang: "ko", expected: "오전 2시" },
    { timeString: "3:00", lang: "ko", expected: "오전 3시" },
    { timeString: "4:00", lang: "ko", expected: "오전 4시" },
    { timeString: "5:00", lang: "ko", expected: "오전 5시" },
    { timeString: "6:00", lang: "ko", expected: "오전 6시" },
    { timeString: "7:00", lang: "ko", expected: "오전 7시" },
    { timeString: "8:00", lang: "ko", expected: "오전 8시" },
    { timeString: "9:00", lang: "ko", expected: "오전 9시" },
    { timeString: "00:00", lang: "ko", expected: "자정" },
    { timeString: "00:10", lang: "ko", expected: "오전 0시 10 분" },
    { timeString: "01:00", lang: "ko", expected: "오전 1시" },
    { timeString: "02:00", lang: "ko", expected: "오전 2시" },
    { timeString: "03:00", lang: "ko", expected: "오전 3시" },
    { timeString: "04:00", lang: "ko", expected: "오전 4시" },
    { timeString: "05:00", lang: "ko", expected: "오전 5시" },
    { timeString: "06:00", lang: "ko", expected: "오전 6시" },
    { timeString: "07:00", lang: "ko", expected: "오전 7시" },
    { timeString: "08:00", lang: "ko", expected: "오전 8시" },
    { timeString: "09:00", lang: "ko", expected: "오전 9시" },
    { timeString: "10:00", lang: "ko", expected: "오전 10시" },
    { timeString: "11:00", lang: "ko", expected: "오전 11시" },
    { timeString: "12:00", lang: "ko", expected: "오후 12시" },
    { timeString: "13:00", lang: "ko", expected: "오후 1시" },
    { timeString: "14:00", lang: "ko", expected: "오후 2시" },
    { timeString: "15:00", lang: "ko", expected: "오후 3시" },
    { timeString: "16:00", lang: "ko", expected: "오후 4시" },
    { timeString: "17:00", lang: "ko", expected: "오후 5시" },
    { timeString: "18:00", lang: "ko", expected: "오후 6시" },
    { timeString: "19:00", lang: "ko", expected: "오후 7시" },
    { timeString: "20:00", lang: "ko", expected: "오후 8시" },
    { timeString: "21:00", lang: "ko", expected: "오후 9시" },
    { timeString: "22:00", lang: "ko", expected: "오후 10시" },
    { timeString: "23:00", lang: "ko", expected: "오후 11시" },
  ];
  datas.forEach((v) => {
    test(`引数に("${v.timeString}", "${v.lang}")を渡すと"${v.expected}"が返ること`, () => {
      expect(ttsTextConverter.convertTime(v.timeString, v.lang)).toBe(v.expected);
    });
  });
});

describe("convertPercentageのテスト", () => {
  const datas = [
    { percentage: 1, lang: "ja", expected: 1 },
    { percentage: 2, lang: "ja", expected: 2 },
    { percentage: 3, lang: "ja", expected: 3 },
    { percentage: 4, lang: "ja", expected: 4 },
    { percentage: 5, lang: "ja", expected: 5 },
    { percentage: 6, lang: "ja", expected: 6 },
    { percentage: 7, lang: "ja", expected: 7 },
    { percentage: 8, lang: "ja", expected: 8 },
    { percentage: 9, lang: "ja", expected: 9 },
    { percentage: 10, lang: "ja", expected: 10 },
    { percentage: 11, lang: "ja", expected: 11 },
    { percentage: 12, lang: "ja", expected: 12 },
    { percentage: 13, lang: "ja", expected: 13 },
    { percentage: 14, lang: "ja", expected: 14 },
    { percentage: 15, lang: "ja", expected: 15 },
    { percentage: 16, lang: "ja", expected: 16 },
    { percentage: 17, lang: "ja", expected: 17 },
    { percentage: 18, lang: "ja", expected: 18 },
    { percentage: 19, lang: "ja", expected: 19 },
    { percentage: 20, lang: "ja", expected: 20 },
    { percentage: 21, lang: "ja", expected: 21 },
    { percentage: 22, lang: "ja", expected: 22 },
    { percentage: 23, lang: "ja", expected: 23 },
    { percentage: 24, lang: "ja", expected: 24 },
    { percentage: 25, lang: "ja", expected: 25 },
    { percentage: 26, lang: "ja", expected: 26 },
    { percentage: 27, lang: "ja", expected: 27 },
    { percentage: 28, lang: "ja", expected: 28 },
    { percentage: 29, lang: "ja", expected: 29 },
    { percentage: 30, lang: "ja", expected: 30 },
    { percentage: 31, lang: "ja", expected: 31 },
    { percentage: 32, lang: "ja", expected: 32 },
    { percentage: 33, lang: "ja", expected: 33 },
    { percentage: 34, lang: "ja", expected: 34 },
    { percentage: 35, lang: "ja", expected: 35 },
    { percentage: 36, lang: "ja", expected: 36 },
    { percentage: 37, lang: "ja", expected: 37 },
    { percentage: 38, lang: "ja", expected: 38 },
    { percentage: 39, lang: "ja", expected: 39 },
    { percentage: 40, lang: "ja", expected: 40 },
    { percentage: 41, lang: "ja", expected: 41 },
    { percentage: 42, lang: "ja", expected: 42 },
    { percentage: 43, lang: "ja", expected: 43 },
    { percentage: 44, lang: "ja", expected: 44 },
    { percentage: 45, lang: "ja", expected: 45 },
    { percentage: 46, lang: "ja", expected: 46 },
    { percentage: 47, lang: "ja", expected: 47 },
    { percentage: 48, lang: "ja", expected: 48 },
    { percentage: 49, lang: "ja", expected: 49 },
    { percentage: 50, lang: "ja", expected: 50 },
    { percentage: 51, lang: "ja", expected: 51 },
    { percentage: 52, lang: "ja", expected: 52 },
    { percentage: 53, lang: "ja", expected: 53 },
    { percentage: 54, lang: "ja", expected: 54 },
    { percentage: 55, lang: "ja", expected: 55 },
    { percentage: 56, lang: "ja", expected: 56 },
    { percentage: 57, lang: "ja", expected: 57 },
    { percentage: 58, lang: "ja", expected: 58 },
    { percentage: 59, lang: "ja", expected: 59 },
    { percentage: 60, lang: "ja", expected: 60 },
    { percentage: 61, lang: "ja", expected: 61 },
    { percentage: 62, lang: "ja", expected: 62 },
    { percentage: 63, lang: "ja", expected: 63 },
    { percentage: 64, lang: "ja", expected: 64 },
    { percentage: 65, lang: "ja", expected: 65 },
    { percentage: 66, lang: "ja", expected: 66 },
    { percentage: 67, lang: "ja", expected: 67 },
    { percentage: 68, lang: "ja", expected: 68 },
    { percentage: 69, lang: "ja", expected: 69 },
    { percentage: 70, lang: "ja", expected: 70 },
    { percentage: 71, lang: "ja", expected: 71 },
    { percentage: 72, lang: "ja", expected: 72 },
    { percentage: 73, lang: "ja", expected: 73 },
    { percentage: 74, lang: "ja", expected: 74 },
    { percentage: 75, lang: "ja", expected: 75 },
    { percentage: 76, lang: "ja", expected: 76 },
    { percentage: 77, lang: "ja", expected: 77 },
    { percentage: 78, lang: "ja", expected: 78 },
    { percentage: 79, lang: "ja", expected: 79 },
    { percentage: 80, lang: "ja", expected: 80 },
    { percentage: 81, lang: "ja", expected: 81 },
    { percentage: 82, lang: "ja", expected: 82 },
    { percentage: 83, lang: "ja", expected: 83 },
    { percentage: 84, lang: "ja", expected: 84 },
    { percentage: 85, lang: "ja", expected: 85 },
    { percentage: 86, lang: "ja", expected: 86 },
    { percentage: 87, lang: "ja", expected: 87 },
    { percentage: 88, lang: "ja", expected: 88 },
    { percentage: 89, lang: "ja", expected: 89 },
    { percentage: 90, lang: "ja", expected: 90 },
    { percentage: 91, lang: "ja", expected: 91 },
    { percentage: 92, lang: "ja", expected: 92 },
    { percentage: 93, lang: "ja", expected: 93 },
    { percentage: 94, lang: "ja", expected: 94 },
    { percentage: 95, lang: "ja", expected: 95 },
    { percentage: 96, lang: "ja", expected: 96 },
    { percentage: 97, lang: "ja", expected: 97 },
    { percentage: 98, lang: "ja", expected: 98 },
    { percentage: 99, lang: "ja", expected: 99 },
    { percentage: 1, lang: "en", expected: 1 },
    { percentage: 2, lang: "en", expected: 2 },
    { percentage: 3, lang: "en", expected: 3 },
    { percentage: 4, lang: "en", expected: 4 },
    { percentage: 5, lang: "en", expected: 5 },
    { percentage: 6, lang: "en", expected: 6 },
    { percentage: 7, lang: "en", expected: 7 },
    { percentage: 8, lang: "en", expected: 8 },
    { percentage: 9, lang: "en", expected: 9 },
    { percentage: 10, lang: "en", expected: 10 },
    { percentage: 11, lang: "en", expected: 11 },
    { percentage: 12, lang: "en", expected: 12 },
    { percentage: 13, lang: "en", expected: 13 },
    { percentage: 14, lang: "en", expected: 14 },
    { percentage: 15, lang: "en", expected: 15 },
    { percentage: 16, lang: "en", expected: 16 },
    { percentage: 17, lang: "en", expected: 17 },
    { percentage: 18, lang: "en", expected: 18 },
    { percentage: 19, lang: "en", expected: 19 },
    { percentage: 20, lang: "en", expected: 20 },
    { percentage: 21, lang: "en", expected: 21 },
    { percentage: 22, lang: "en", expected: 22 },
    { percentage: 23, lang: "en", expected: 23 },
    { percentage: 24, lang: "en", expected: 24 },
    { percentage: 25, lang: "en", expected: 25 },
    { percentage: 26, lang: "en", expected: 26 },
    { percentage: 27, lang: "en", expected: 27 },
    { percentage: 28, lang: "en", expected: 28 },
    { percentage: 29, lang: "en", expected: 29 },
    { percentage: 30, lang: "en", expected: 30 },
    { percentage: 31, lang: "en", expected: 31 },
    { percentage: 32, lang: "en", expected: 32 },
    { percentage: 33, lang: "en", expected: 33 },
    { percentage: 34, lang: "en", expected: 34 },
    { percentage: 35, lang: "en", expected: 35 },
    { percentage: 36, lang: "en", expected: 36 },
    { percentage: 37, lang: "en", expected: 37 },
    { percentage: 38, lang: "en", expected: 38 },
    { percentage: 39, lang: "en", expected: 39 },
    { percentage: 40, lang: "en", expected: 40 },
    { percentage: 41, lang: "en", expected: 41 },
    { percentage: 42, lang: "en", expected: 42 },
    { percentage: 43, lang: "en", expected: 43 },
    { percentage: 44, lang: "en", expected: 44 },
    { percentage: 45, lang: "en", expected: 45 },
    { percentage: 46, lang: "en", expected: 46 },
    { percentage: 47, lang: "en", expected: 47 },
    { percentage: 48, lang: "en", expected: 48 },
    { percentage: 49, lang: "en", expected: 49 },
    { percentage: 50, lang: "en", expected: 50 },
    { percentage: 51, lang: "en", expected: 51 },
    { percentage: 52, lang: "en", expected: 52 },
    { percentage: 53, lang: "en", expected: 53 },
    { percentage: 54, lang: "en", expected: 54 },
    { percentage: 55, lang: "en", expected: 55 },
    { percentage: 56, lang: "en", expected: 56 },
    { percentage: 57, lang: "en", expected: 57 },
    { percentage: 58, lang: "en", expected: 58 },
    { percentage: 59, lang: "en", expected: 59 },
    { percentage: 60, lang: "en", expected: 60 },
    { percentage: 61, lang: "en", expected: 61 },
    { percentage: 62, lang: "en", expected: 62 },
    { percentage: 63, lang: "en", expected: 63 },
    { percentage: 64, lang: "en", expected: 64 },
    { percentage: 65, lang: "en", expected: 65 },
    { percentage: 66, lang: "en", expected: 66 },
    { percentage: 67, lang: "en", expected: 67 },
    { percentage: 68, lang: "en", expected: 68 },
    { percentage: 69, lang: "en", expected: 69 },
    { percentage: 70, lang: "en", expected: 70 },
    { percentage: 71, lang: "en", expected: 71 },
    { percentage: 72, lang: "en", expected: 72 },
    { percentage: 73, lang: "en", expected: 73 },
    { percentage: 74, lang: "en", expected: 74 },
    { percentage: 75, lang: "en", expected: 75 },
    { percentage: 76, lang: "en", expected: 76 },
    { percentage: 77, lang: "en", expected: 77 },
    { percentage: 78, lang: "en", expected: 78 },
    { percentage: 79, lang: "en", expected: 79 },
    { percentage: 80, lang: "en", expected: 80 },
    { percentage: 81, lang: "en", expected: 81 },
    { percentage: 82, lang: "en", expected: 82 },
    { percentage: 83, lang: "en", expected: 83 },
    { percentage: 84, lang: "en", expected: 84 },
    { percentage: 85, lang: "en", expected: 85 },
    { percentage: 86, lang: "en", expected: 86 },
    { percentage: 87, lang: "en", expected: 87 },
    { percentage: 88, lang: "en", expected: 88 },
    { percentage: 89, lang: "en", expected: 89 },
    { percentage: 90, lang: "en", expected: 90 },
    { percentage: 91, lang: "en", expected: 91 },
    { percentage: 92, lang: "en", expected: 92 },
    { percentage: 93, lang: "en", expected: 93 },
    { percentage: 94, lang: "en", expected: 94 },
    { percentage: 95, lang: "en", expected: 95 },
    { percentage: 96, lang: "en", expected: 96 },
    { percentage: 97, lang: "en", expected: 97 },
    { percentage: 98, lang: "en", expected: 98 },
    { percentage: 99, lang: "en", expected: 99 },
    { percentage: 1, lang: "zh", expected: 9.9 },
    { percentage: 2, lang: "zh", expected: 9.8 },
    { percentage: 3, lang: "zh", expected: 9.7 },
    { percentage: 4, lang: "zh", expected: 9.6 },
    { percentage: 5, lang: "zh", expected: 9.5 },
    { percentage: 6, lang: "zh", expected: 9.4 },
    { percentage: 7, lang: "zh", expected: 9.3 },
    { percentage: 8, lang: "zh", expected: 9.2 },
    { percentage: 9, lang: "zh", expected: 9.1 },
    { percentage: 10, lang: "zh", expected: 9 },
    { percentage: 11, lang: "zh", expected: 8.9 },
    { percentage: 12, lang: "zh", expected: 8.8 },
    { percentage: 13, lang: "zh", expected: 8.7 },
    { percentage: 14, lang: "zh", expected: 8.6 },
    { percentage: 15, lang: "zh", expected: 8.5 },
    { percentage: 16, lang: "zh", expected: 8.4 },
    { percentage: 17, lang: "zh", expected: 8.3 },
    { percentage: 18, lang: "zh", expected: 8.2 },
    { percentage: 19, lang: "zh", expected: 8.1 },
    { percentage: 20, lang: "zh", expected: 8 },
    { percentage: 21, lang: "zh", expected: 7.9 },
    { percentage: 22, lang: "zh", expected: 7.8 },
    { percentage: 23, lang: "zh", expected: 7.7 },
    { percentage: 24, lang: "zh", expected: 7.6 },
    { percentage: 25, lang: "zh", expected: 7.5 },
    { percentage: 26, lang: "zh", expected: 7.4 },
    { percentage: 27, lang: "zh", expected: 7.3 },
    { percentage: 28, lang: "zh", expected: 7.2 },
    { percentage: 29, lang: "zh", expected: 7.1 },
    { percentage: 30, lang: "zh", expected: 7 },
    { percentage: 31, lang: "zh", expected: 6.9 },
    { percentage: 32, lang: "zh", expected: 6.8 },
    { percentage: 33, lang: "zh", expected: 6.7 },
    { percentage: 34, lang: "zh", expected: 6.6 },
    { percentage: 35, lang: "zh", expected: 6.5 },
    { percentage: 36, lang: "zh", expected: 6.4 },
    { percentage: 37, lang: "zh", expected: 6.3 },
    { percentage: 38, lang: "zh", expected: 6.2 },
    { percentage: 39, lang: "zh", expected: 6.1 },
    { percentage: 40, lang: "zh", expected: 6 },
    { percentage: 41, lang: "zh", expected: 5.9 },
    { percentage: 42, lang: "zh", expected: 5.8 },
    { percentage: 43, lang: "zh", expected: 5.7 },
    { percentage: 44, lang: "zh", expected: 5.6 },
    { percentage: 45, lang: "zh", expected: 5.5 },
    { percentage: 46, lang: "zh", expected: 5.4 },
    { percentage: 47, lang: "zh", expected: 5.3 },
    { percentage: 48, lang: "zh", expected: 5.2 },
    { percentage: 49, lang: "zh", expected: 5.1 },
    { percentage: 50, lang: "zh", expected: 5 },
    { percentage: 51, lang: "zh", expected: 4.9 },
    { percentage: 52, lang: "zh", expected: 4.8 },
    { percentage: 53, lang: "zh", expected: 4.7 },
    { percentage: 54, lang: "zh", expected: 4.6 },
    { percentage: 55, lang: "zh", expected: 4.5 },
    { percentage: 56, lang: "zh", expected: 4.4 },
    { percentage: 57, lang: "zh", expected: 4.3 },
    { percentage: 58, lang: "zh", expected: 4.2 },
    { percentage: 59, lang: "zh", expected: 4.1 },
    { percentage: 60, lang: "zh", expected: 4 },
    { percentage: 61, lang: "zh", expected: 3.9 },
    { percentage: 62, lang: "zh", expected: 3.8 },
    { percentage: 63, lang: "zh", expected: 3.7 },
    { percentage: 64, lang: "zh", expected: 3.6 },
    { percentage: 65, lang: "zh", expected: 3.5 },
    { percentage: 66, lang: "zh", expected: 3.4 },
    { percentage: 67, lang: "zh", expected: 3.3 },
    { percentage: 68, lang: "zh", expected: 3.2 },
    { percentage: 69, lang: "zh", expected: 3.1 },
    { percentage: 70, lang: "zh", expected: 3 },
    { percentage: 71, lang: "zh", expected: 2.9 },
    { percentage: 72, lang: "zh", expected: 2.8 },
    { percentage: 73, lang: "zh", expected: 2.7 },
    { percentage: 74, lang: "zh", expected: 2.6 },
    { percentage: 75, lang: "zh", expected: 2.5 },
    { percentage: 76, lang: "zh", expected: 2.4 },
    { percentage: 77, lang: "zh", expected: 2.3 },
    { percentage: 78, lang: "zh", expected: 2.2 },
    { percentage: 79, lang: "zh", expected: 2.1 },
    { percentage: 80, lang: "zh", expected: 2 },
    { percentage: 81, lang: "zh", expected: 1.9 },
    { percentage: 82, lang: "zh", expected: 1.8 },
    { percentage: 83, lang: "zh", expected: 1.7 },
    { percentage: 84, lang: "zh", expected: 1.6 },
    { percentage: 85, lang: "zh", expected: 1.5 },
    { percentage: 86, lang: "zh", expected: 1.4 },
    { percentage: 87, lang: "zh", expected: 1.3 },
    { percentage: 88, lang: "zh", expected: 1.2 },
    { percentage: 89, lang: "zh", expected: 1.1 },
    { percentage: 90, lang: "zh", expected: 1 },
    { percentage: 91, lang: "zh", expected: 0.9 },
    { percentage: 92, lang: "zh", expected: 0.8 },
    { percentage: 93, lang: "zh", expected: 0.7 },
    { percentage: 94, lang: "zh", expected: 0.6 },
    { percentage: 95, lang: "zh", expected: 0.5 },
    { percentage: 96, lang: "zh", expected: 0.4 },
    { percentage: 97, lang: "zh", expected: 0.3 },
    { percentage: 98, lang: "zh", expected: 0.2 },
    { percentage: 99, lang: "zh", expected: 0.1 },
    { percentage: 1, lang: "ko", expected: 1 },
    { percentage: 2, lang: "ko", expected: 2 },
    { percentage: 3, lang: "ko", expected: 3 },
    { percentage: 4, lang: "ko", expected: 4 },
    { percentage: 5, lang: "ko", expected: 5 },
    { percentage: 6, lang: "ko", expected: 6 },
    { percentage: 7, lang: "ko", expected: 7 },
    { percentage: 8, lang: "ko", expected: 8 },
    { percentage: 9, lang: "ko", expected: 9 },
    { percentage: 10, lang: "ko", expected: 10 },
    { percentage: 11, lang: "ko", expected: 11 },
    { percentage: 12, lang: "ko", expected: 12 },
    { percentage: 13, lang: "ko", expected: 13 },
    { percentage: 14, lang: "ko", expected: 14 },
    { percentage: 15, lang: "ko", expected: 15 },
    { percentage: 16, lang: "ko", expected: 16 },
    { percentage: 17, lang: "ko", expected: 17 },
    { percentage: 18, lang: "ko", expected: 18 },
    { percentage: 19, lang: "ko", expected: 19 },
    { percentage: 20, lang: "ko", expected: 20 },
    { percentage: 21, lang: "ko", expected: 21 },
    { percentage: 22, lang: "ko", expected: 22 },
    { percentage: 23, lang: "ko", expected: 23 },
    { percentage: 24, lang: "ko", expected: 24 },
    { percentage: 25, lang: "ko", expected: 25 },
    { percentage: 26, lang: "ko", expected: 26 },
    { percentage: 27, lang: "ko", expected: 27 },
    { percentage: 28, lang: "ko", expected: 28 },
    { percentage: 29, lang: "ko", expected: 29 },
    { percentage: 30, lang: "ko", expected: 30 },
    { percentage: 31, lang: "ko", expected: 31 },
    { percentage: 32, lang: "ko", expected: 32 },
    { percentage: 33, lang: "ko", expected: 33 },
    { percentage: 34, lang: "ko", expected: 34 },
    { percentage: 35, lang: "ko", expected: 35 },
    { percentage: 36, lang: "ko", expected: 36 },
    { percentage: 37, lang: "ko", expected: 37 },
    { percentage: 38, lang: "ko", expected: 38 },
    { percentage: 39, lang: "ko", expected: 39 },
    { percentage: 40, lang: "ko", expected: 40 },
    { percentage: 41, lang: "ko", expected: 41 },
    { percentage: 42, lang: "ko", expected: 42 },
    { percentage: 43, lang: "ko", expected: 43 },
    { percentage: 44, lang: "ko", expected: 44 },
    { percentage: 45, lang: "ko", expected: 45 },
    { percentage: 46, lang: "ko", expected: 46 },
    { percentage: 47, lang: "ko", expected: 47 },
    { percentage: 48, lang: "ko", expected: 48 },
    { percentage: 49, lang: "ko", expected: 49 },
    { percentage: 50, lang: "ko", expected: 50 },
    { percentage: 51, lang: "ko", expected: 51 },
    { percentage: 52, lang: "ko", expected: 52 },
    { percentage: 53, lang: "ko", expected: 53 },
    { percentage: 54, lang: "ko", expected: 54 },
    { percentage: 55, lang: "ko", expected: 55 },
    { percentage: 56, lang: "ko", expected: 56 },
    { percentage: 57, lang: "ko", expected: 57 },
    { percentage: 58, lang: "ko", expected: 58 },
    { percentage: 59, lang: "ko", expected: 59 },
    { percentage: 60, lang: "ko", expected: 60 },
    { percentage: 61, lang: "ko", expected: 61 },
    { percentage: 62, lang: "ko", expected: 62 },
    { percentage: 63, lang: "ko", expected: 63 },
    { percentage: 64, lang: "ko", expected: 64 },
    { percentage: 65, lang: "ko", expected: 65 },
    { percentage: 66, lang: "ko", expected: 66 },
    { percentage: 67, lang: "ko", expected: 67 },
    { percentage: 68, lang: "ko", expected: 68 },
    { percentage: 69, lang: "ko", expected: 69 },
    { percentage: 70, lang: "ko", expected: 70 },
    { percentage: 71, lang: "ko", expected: 71 },
    { percentage: 72, lang: "ko", expected: 72 },
    { percentage: 73, lang: "ko", expected: 73 },
    { percentage: 74, lang: "ko", expected: 74 },
    { percentage: 75, lang: "ko", expected: 75 },
    { percentage: 76, lang: "ko", expected: 76 },
    { percentage: 77, lang: "ko", expected: 77 },
    { percentage: 78, lang: "ko", expected: 78 },
    { percentage: 79, lang: "ko", expected: 79 },
    { percentage: 80, lang: "ko", expected: 80 },
    { percentage: 81, lang: "ko", expected: 81 },
    { percentage: 82, lang: "ko", expected: 82 },
    { percentage: 83, lang: "ko", expected: 83 },
    { percentage: 84, lang: "ko", expected: 84 },
    { percentage: 85, lang: "ko", expected: 85 },
    { percentage: 86, lang: "ko", expected: 86 },
    { percentage: 87, lang: "ko", expected: 87 },
    { percentage: 88, lang: "ko", expected: 88 },
    { percentage: 89, lang: "ko", expected: 89 },
    { percentage: 90, lang: "ko", expected: 90 },
    { percentage: 91, lang: "ko", expected: 91 },
    { percentage: 92, lang: "ko", expected: 92 },
    { percentage: 93, lang: "ko", expected: 93 },
    { percentage: 94, lang: "ko", expected: 94 },
    { percentage: 95, lang: "ko", expected: 95 },
    { percentage: 96, lang: "ko", expected: 96 },
    { percentage: 97, lang: "ko", expected: 97 },
    { percentage: 98, lang: "ko", expected: 98 },
    { percentage: 99, lang: "ko", expected: 99 },
  ];
  datas.forEach((v) => {
    test(`引数に("${v.percentage}", "${v.lang}")を渡すと"${v.expected}"が返ること`, () => {
      expect(ttsTextConverter.convertPercentage(v.percentage, v.lang)).toBe(v.expected);
    });
  });
});

describe("convertEndYearDateのテスト", () => {
  const datas = [
    { dateString: "12/1", lang: "ja", expected: "1" },
    { dateString: "12/2", lang: "ja", expected: "2" },
    { dateString: "12/3", lang: "ja", expected: "3" },
    { dateString: "12/4", lang: "ja", expected: "4" },
    { dateString: "12/5", lang: "ja", expected: "5" },
    { dateString: "12/6", lang: "ja", expected: "6" },
    { dateString: "12/7", lang: "ja", expected: "7" },
    { dateString: "12/8", lang: "ja", expected: "8" },
    { dateString: "12/9", lang: "ja", expected: "9" },
    { dateString: "12/10", lang: "ja", expected: "10" },
    { dateString: "12/11", lang: "ja", expected: "11" },
    { dateString: "12/12", lang: "ja", expected: "12" },
    { dateString: "12/13", lang: "ja", expected: "13" },
    { dateString: "12/14", lang: "ja", expected: "14" },
    { dateString: "12/15", lang: "ja", expected: "15" },
    { dateString: "12/16", lang: "ja", expected: "16" },
    { dateString: "12/17", lang: "ja", expected: "17" },
    { dateString: "12/18", lang: "ja", expected: "18" },
    { dateString: "12/19", lang: "ja", expected: "19" },
    { dateString: "12/20", lang: "ja", expected: "20" },
    { dateString: "12/21", lang: "ja", expected: "21" },
    { dateString: "12/22", lang: "ja", expected: "22" },
    { dateString: "12/23", lang: "ja", expected: "23" },
    { dateString: "12/24", lang: "ja", expected: "24" },
    { dateString: "12/25", lang: "ja", expected: "25" },
    { dateString: "12/26", lang: "ja", expected: "26" },
    { dateString: "12/27", lang: "ja", expected: "27" },
    { dateString: "12/28", lang: "ja", expected: "28" },
    { dateString: "12/29", lang: "ja", expected: "29" },
    { dateString: "12/30", lang: "ja", expected: "30" },
    { dateString: "12/31", lang: "ja", expected: "31" },
    { dateString: "12/1", lang: "en", expected: "1st" },
    { dateString: "12/2", lang: "en", expected: "2nd" },
    { dateString: "12/3", lang: "en", expected: "3rd" },
    { dateString: "12/4", lang: "en", expected: "4th" },
    { dateString: "12/5", lang: "en", expected: "5th" },
    { dateString: "12/6", lang: "en", expected: "6th" },
    { dateString: "12/7", lang: "en", expected: "7th" },
    { dateString: "12/8", lang: "en", expected: "8th" },
    { dateString: "12/9", lang: "en", expected: "9th" },
    { dateString: "12/10", lang: "en", expected: "10th" },
    { dateString: "12/11", lang: "en", expected: "11th" },
    { dateString: "12/12", lang: "en", expected: "12th" },
    { dateString: "12/13", lang: "en", expected: "13th" },
    { dateString: "12/14", lang: "en", expected: "14th" },
    { dateString: "12/15", lang: "en", expected: "15th" },
    { dateString: "12/16", lang: "en", expected: "16th" },
    { dateString: "12/17", lang: "en", expected: "17th" },
    { dateString: "12/18", lang: "en", expected: "18th" },
    { dateString: "12/19", lang: "en", expected: "19th" },
    { dateString: "12/20", lang: "en", expected: "20th" },
    { dateString: "12/21", lang: "en", expected: "21th" },
    { dateString: "12/22", lang: "en", expected: "22th" },
    { dateString: "12/23", lang: "en", expected: "23th" },
    { dateString: "12/24", lang: "en", expected: "24th" },
    { dateString: "12/25", lang: "en", expected: "25th" },
    { dateString: "12/26", lang: "en", expected: "26th" },
    { dateString: "12/27", lang: "en", expected: "27th" },
    { dateString: "12/28", lang: "en", expected: "28th" },
    { dateString: "12/29", lang: "en", expected: "29th" },
    { dateString: "12/30", lang: "en", expected: "30th" },
    { dateString: "12/31", lang: "en", expected: "31th" },
    { dateString: "12/1", lang: "zh", expected: "1" },
    { dateString: "12/2", lang: "zh", expected: "2" },
    { dateString: "12/3", lang: "zh", expected: "3" },
    { dateString: "12/4", lang: "zh", expected: "4" },
    { dateString: "12/5", lang: "zh", expected: "5" },
    { dateString: "12/6", lang: "zh", expected: "6" },
    { dateString: "12/7", lang: "zh", expected: "7" },
    { dateString: "12/8", lang: "zh", expected: "8" },
    { dateString: "12/9", lang: "zh", expected: "9" },
    { dateString: "12/10", lang: "zh", expected: "10" },
    { dateString: "12/11", lang: "zh", expected: "11" },
    { dateString: "12/12", lang: "zh", expected: "12" },
    { dateString: "12/13", lang: "zh", expected: "13" },
    { dateString: "12/14", lang: "zh", expected: "14" },
    { dateString: "12/15", lang: "zh", expected: "15" },
    { dateString: "12/16", lang: "zh", expected: "16" },
    { dateString: "12/17", lang: "zh", expected: "17" },
    { dateString: "12/18", lang: "zh", expected: "18" },
    { dateString: "12/19", lang: "zh", expected: "19" },
    { dateString: "12/20", lang: "zh", expected: "20" },
    { dateString: "12/21", lang: "zh", expected: "21" },
    { dateString: "12/22", lang: "zh", expected: "22" },
    { dateString: "12/23", lang: "zh", expected: "23" },
    { dateString: "12/24", lang: "zh", expected: "24" },
    { dateString: "12/25", lang: "zh", expected: "25" },
    { dateString: "12/26", lang: "zh", expected: "26" },
    { dateString: "12/27", lang: "zh", expected: "27" },
    { dateString: "12/28", lang: "zh", expected: "28" },
    { dateString: "12/29", lang: "zh", expected: "29" },
    { dateString: "12/30", lang: "zh", expected: "30" },
    { dateString: "12/31", lang: "zh", expected: "31" },
    { dateString: "12/1", lang: "ko", expected: "1" },
    { dateString: "12/2", lang: "ko", expected: "2" },
    { dateString: "12/3", lang: "ko", expected: "3" },
    { dateString: "12/4", lang: "ko", expected: "4" },
    { dateString: "12/5", lang: "ko", expected: "5" },
    { dateString: "12/6", lang: "ko", expected: "6" },
    { dateString: "12/7", lang: "ko", expected: "7" },
    { dateString: "12/8", lang: "ko", expected: "8" },
    { dateString: "12/9", lang: "ko", expected: "9" },
    { dateString: "12/10", lang: "ko", expected: "10" },
    { dateString: "12/11", lang: "ko", expected: "11" },
    { dateString: "12/12", lang: "ko", expected: "12" },
    { dateString: "12/13", lang: "ko", expected: "13" },
    { dateString: "12/14", lang: "ko", expected: "14" },
    { dateString: "12/15", lang: "ko", expected: "15" },
    { dateString: "12/16", lang: "ko", expected: "16" },
    { dateString: "12/17", lang: "ko", expected: "17" },
    { dateString: "12/18", lang: "ko", expected: "18" },
    { dateString: "12/19", lang: "ko", expected: "19" },
    { dateString: "12/20", lang: "ko", expected: "20" },
    { dateString: "12/21", lang: "ko", expected: "21" },
    { dateString: "12/22", lang: "ko", expected: "22" },
    { dateString: "12/23", lang: "ko", expected: "23" },
    { dateString: "12/24", lang: "ko", expected: "24" },
    { dateString: "12/25", lang: "ko", expected: "25" },
    { dateString: "12/26", lang: "ko", expected: "26" },
    { dateString: "12/27", lang: "ko", expected: "27" },
    { dateString: "12/28", lang: "ko", expected: "28" },
    { dateString: "12/29", lang: "ko", expected: "29" },
    { dateString: "12/30", lang: "ko", expected: "30" },
    { dateString: "12/31", lang: "ko", expected: "31" },
  ];
  datas.forEach((v) => {
    test(`引数に("${v.dateString}", "${v.lang}")を渡すと"${v.expected}"が返ること`, () => {
      expect(ttsTextConverter.convertEndYearDate(v.dateString, v.lang)).toBe(v.expected);
    });
  });
});

describe("convertNewYearDateのテスト", () => {
  const datas = [
    { dateString: "1/1", lang: "ja", expected: "1" },
    { dateString: "1/2", lang: "ja", expected: "2" },
    { dateString: "1/3", lang: "ja", expected: "3" },
    { dateString: "1/4", lang: "ja", expected: "4" },
    { dateString: "1/5", lang: "ja", expected: "5" },
    { dateString: "1/6", lang: "ja", expected: "6" },
    { dateString: "1/7", lang: "ja", expected: "7" },
    { dateString: "1/8", lang: "ja", expected: "8" },
    { dateString: "1/9", lang: "ja", expected: "9" },
    { dateString: "1/10", lang: "ja", expected: "10" },
    { dateString: "1/11", lang: "ja", expected: "11" },
    { dateString: "1/12", lang: "ja", expected: "12" },
    { dateString: "1/13", lang: "ja", expected: "13" },
    { dateString: "1/14", lang: "ja", expected: "14" },
    { dateString: "1/15", lang: "ja", expected: "15" },
    { dateString: "1/16", lang: "ja", expected: "16" },
    { dateString: "1/17", lang: "ja", expected: "17" },
    { dateString: "1/18", lang: "ja", expected: "18" },
    { dateString: "1/19", lang: "ja", expected: "19" },
    { dateString: "1/20", lang: "ja", expected: "20" },
    { dateString: "1/21", lang: "ja", expected: "21" },
    { dateString: "1/22", lang: "ja", expected: "22" },
    { dateString: "1/23", lang: "ja", expected: "23" },
    { dateString: "1/24", lang: "ja", expected: "24" },
    { dateString: "1/25", lang: "ja", expected: "25" },
    { dateString: "1/26", lang: "ja", expected: "26" },
    { dateString: "1/27", lang: "ja", expected: "27" },
    { dateString: "1/28", lang: "ja", expected: "28" },
    { dateString: "1/29", lang: "ja", expected: "29" },
    { dateString: "1/30", lang: "ja", expected: "30" },
    { dateString: "1/31", lang: "ja", expected: "31" },
    { dateString: "1/1", lang: "en", expected: "1st" },
    { dateString: "1/2", lang: "en", expected: "2nd" },
    { dateString: "1/3", lang: "en", expected: "3rd" },
    { dateString: "1/4", lang: "en", expected: "4th" },
    { dateString: "1/5", lang: "en", expected: "5th" },
    { dateString: "1/6", lang: "en", expected: "6th" },
    { dateString: "1/7", lang: "en", expected: "7th" },
    { dateString: "1/8", lang: "en", expected: "8th" },
    { dateString: "1/9", lang: "en", expected: "9th" },
    { dateString: "1/10", lang: "en", expected: "10th" },
    { dateString: "1/11", lang: "en", expected: "11th" },
    { dateString: "1/12", lang: "en", expected: "12th" },
    { dateString: "1/13", lang: "en", expected: "13th" },
    { dateString: "1/14", lang: "en", expected: "14th" },
    { dateString: "1/15", lang: "en", expected: "15th" },
    { dateString: "1/16", lang: "en", expected: "16th" },
    { dateString: "1/17", lang: "en", expected: "17th" },
    { dateString: "1/18", lang: "en", expected: "18th" },
    { dateString: "1/19", lang: "en", expected: "19th" },
    { dateString: "1/20", lang: "en", expected: "20th" },
    { dateString: "1/21", lang: "en", expected: "21th" },
    { dateString: "1/22", lang: "en", expected: "22th" },
    { dateString: "1/23", lang: "en", expected: "23th" },
    { dateString: "1/24", lang: "en", expected: "24th" },
    { dateString: "1/25", lang: "en", expected: "25th" },
    { dateString: "1/26", lang: "en", expected: "26th" },
    { dateString: "1/27", lang: "en", expected: "27th" },
    { dateString: "1/28", lang: "en", expected: "28th" },
    { dateString: "1/29", lang: "en", expected: "29th" },
    { dateString: "1/30", lang: "en", expected: "30th" },
    { dateString: "1/31", lang: "en", expected: "31th" },
    { dateString: "1/1", lang: "zh", expected: "1" },
    { dateString: "1/2", lang: "zh", expected: "2" },
    { dateString: "1/3", lang: "zh", expected: "3" },
    { dateString: "1/4", lang: "zh", expected: "4" },
    { dateString: "1/5", lang: "zh", expected: "5" },
    { dateString: "1/6", lang: "zh", expected: "6" },
    { dateString: "1/7", lang: "zh", expected: "7" },
    { dateString: "1/8", lang: "zh", expected: "8" },
    { dateString: "1/9", lang: "zh", expected: "9" },
    { dateString: "1/10", lang: "zh", expected: "10" },
    { dateString: "1/11", lang: "zh", expected: "11" },
    { dateString: "1/12", lang: "zh", expected: "12" },
    { dateString: "1/13", lang: "zh", expected: "13" },
    { dateString: "1/14", lang: "zh", expected: "14" },
    { dateString: "1/15", lang: "zh", expected: "15" },
    { dateString: "1/16", lang: "zh", expected: "16" },
    { dateString: "1/17", lang: "zh", expected: "17" },
    { dateString: "1/18", lang: "zh", expected: "18" },
    { dateString: "1/19", lang: "zh", expected: "19" },
    { dateString: "1/20", lang: "zh", expected: "20" },
    { dateString: "1/21", lang: "zh", expected: "21" },
    { dateString: "1/22", lang: "zh", expected: "22" },
    { dateString: "1/23", lang: "zh", expected: "23" },
    { dateString: "1/24", lang: "zh", expected: "24" },
    { dateString: "1/25", lang: "zh", expected: "25" },
    { dateString: "1/26", lang: "zh", expected: "26" },
    { dateString: "1/27", lang: "zh", expected: "27" },
    { dateString: "1/28", lang: "zh", expected: "28" },
    { dateString: "1/29", lang: "zh", expected: "29" },
    { dateString: "1/30", lang: "zh", expected: "30" },
    { dateString: "1/31", lang: "zh", expected: "31" },
    { dateString: "1/1", lang: "ko", expected: "1" },
    { dateString: "1/2", lang: "ko", expected: "2" },
    { dateString: "1/3", lang: "ko", expected: "3" },
    { dateString: "1/4", lang: "ko", expected: "4" },
    { dateString: "1/5", lang: "ko", expected: "5" },
    { dateString: "1/6", lang: "ko", expected: "6" },
    { dateString: "1/7", lang: "ko", expected: "7" },
    { dateString: "1/8", lang: "ko", expected: "8" },
    { dateString: "1/9", lang: "ko", expected: "9" },
    { dateString: "1/10", lang: "ko", expected: "10" },
    { dateString: "1/11", lang: "ko", expected: "11" },
    { dateString: "1/12", lang: "ko", expected: "12" },
    { dateString: "1/13", lang: "ko", expected: "13" },
    { dateString: "1/14", lang: "ko", expected: "14" },
    { dateString: "1/15", lang: "ko", expected: "15" },
    { dateString: "1/16", lang: "ko", expected: "16" },
    { dateString: "1/17", lang: "ko", expected: "17" },
    { dateString: "1/18", lang: "ko", expected: "18" },
    { dateString: "1/19", lang: "ko", expected: "19" },
    { dateString: "1/20", lang: "ko", expected: "20" },
    { dateString: "1/21", lang: "ko", expected: "21" },
    { dateString: "1/22", lang: "ko", expected: "22" },
    { dateString: "1/23", lang: "ko", expected: "23" },
    { dateString: "1/24", lang: "ko", expected: "24" },
    { dateString: "1/25", lang: "ko", expected: "25" },
    { dateString: "1/26", lang: "ko", expected: "26" },
    { dateString: "1/27", lang: "ko", expected: "27" },
    { dateString: "1/28", lang: "ko", expected: "28" },
    { dateString: "1/29", lang: "ko", expected: "29" },
    { dateString: "1/30", lang: "ko", expected: "30" },
    { dateString: "1/31", lang: "ko", expected: "31" },
  ];
  datas.forEach((v) => {
    test(`引数に("${v.dateString}", "${v.lang}")を渡すと"${v.expected}"が返ること`, () => {
      expect(ttsTextConverter.convertNewYearDate(v.dateString, v.lang)).toBe(v.expected);
    });
  });
});

describe("convertManuscriptのテスト", () => {
  const datas = [
    {
      manuscript: "皆さん、おはようございます。只今、開店${minutes}分前です。お客様をお迎えするために、各自準備をすすめてください。服装は清潔にしていますか？店内の清掃は⾏き届いていますか？テーブルなどのセッティングは整っていますか？接客時は丁寧な⾔葉遣いを⼼がけましょう。今⽇も⼀⽇、お客様に気持ちよくお食事していただけるよう⼀人ひとりが最善をつくしましょう。只今、開店${minutes}分前です。",
      lang: "ja",
      customerName: "",
      time: "",
      percentage: 100,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "皆さん、おはようございます。只今、開店10分前です。お客様をお迎えするために、各自準備をすすめてください。服装は清潔にしていますか？店内の清掃は⾏き届いていますか？テーブルなどのセッティングは整っていますか？接客時は丁寧な⾔葉遣いを⼼がけましょう。今⽇も⼀⽇、お客様に気持ちよくお食事していただけるよう⼀人ひとりが最善をつくしましょう。只今、開店10分前です。",
    },
    {
      manuscript: "本⽇は、${customerName}にご来店いただきまして、誠にありがとうございます。お客様にご案内申し上げます。当店の営業時間は${time}までとなっております。本⽇は、ご利⽤ありがとうございます。どうぞごゆっくりお過ごしくださいませ。",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 100,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "本⽇は、ユーセンカフェにご来店いただきまして、誠にありがとうございます。お客様にご案内申し上げます。当店の営業時間は午後9時までとなっております。本⽇は、ご利⽤ありがとうございます。どうぞごゆっくりお過ごしくださいませ。",
    },
    {
      manuscript: "Thank you for visiting us today. The following is an announcement for our customers. We are open until ${time}. We thank you for visiting us today. We hope you enjoy your time here with us today.",
      lang: "en",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 100,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "Thank you for visiting us today. The following is an announcement for our customers. We are open until 9:00 p.m. We thank you for visiting us today. We hope you enjoy your time here with us today.",
    },
    {
      manuscript: "衷心感谢各位顾客今天的光临。下面为您广播通知。本店的营业时间截止至${time}。感谢您今天的惠顾。祝您度过一段轻松愉快的时光。",
      lang: "zh",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 100,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "衷心感谢各位顾客今天的光临。下面为您广播通知。本店的营业时间截止至晚上9点。感谢您今天的惠顾。祝您度过一段轻松愉快的时光。",
    },
    {
      manuscript: "오늘도 방문해 주셔서 대단히 감사합니다. 고객님께 안내 말씀드립니다. 저희 매장의 영업시간은 ${time}까지입니다. 오늘도 이용해 주셔서 감사합니다. 편안한 시간 보내시기 바랍니다.",
      lang: "ko",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 100,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "오늘도 방문해 주셔서 대단히 감사합니다. 고객님께 안내 말씀드립니다. 저희 매장의 영업시간은 오후 9시까지입니다. 오늘도 이용해 주셔서 감사합니다. 편안한 시간 보내시기 바랍니다.",
    },
    {
      manuscript: "いらっしゃいませ。${customerName}では、ただ今、特別セールを実施中！各有名メーカーの商品がなんと${percentage}パーセントオフ！この機会をお⾒逃し無く！ なお一部セール除外品もございますのでご了承ください。本日はご来店誠にありがとうございます。",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 50,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "いらっしゃいませ。ユーセンカフェでは、ただ今、特別セールを実施中！各有名メーカーの商品がなんと50パーセントオフ！この機会をお⾒逃し無く！ なお一部セール除外品もございますのでご了承ください。本日はご来店誠にありがとうございます。",
    },
    {
      manuscript: "欢迎光临。本店现正在举办特价优惠活动！各种名牌商品现正${percentage}折出售！请各位顾客莫失良机！另外，部分商品不参与本次活动，敬请理解。再次衷心感谢您今天的光临。",
      lang: "zh",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 50,
      count: 100,
      endYearDate: "",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "欢迎光临。本店现正在举办特价优惠活动！各种名牌商品现正5折出售！请各位顾客莫失良机！另外，部分商品不参与本次活动，敬请理解。再次衷心感谢您今天的光临。",
    },
    {
      manuscript: "本日も、${customerName}をご利⽤いただきまして誠にありがとうございます。お客様にご案内申し上げます。誠に勝⼿ながら、年内${date1}日までの営業とさせていただきます。ご了承くださいますよう、宜しくお願い申し上げます。",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 50,
      count: 100,
      endYearDate: "12/30",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "本日も、ユーセンカフェをご利⽤いただきまして誠にありがとうございます。お客様にご案内申し上げます。誠に勝⼿ながら、年内30日までの営業とさせていただきます。ご了承くださいますよう、宜しくお願い申し上げます。",
    },
    {
      manuscript: "本日は、${customerName}をご利⽤いただきまして誠にありがとうございます。お客様にご案内申し上げます。試着室への商品のお持込は１回、${number}点迄とさせて頂いております。ご理解、ご協⼒の程、宜しくお願い申し上げます。本日のご利⽤、誠にありがとうございます。",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "21:00",
      percentage: 50,
      count: 3,
      endYearDate: "12/30",
      newYearDate: "",
      age: 100,
      minutes: 10,
      point: 100,
      expected: "本日は、ユーセンカフェをご利⽤いただきまして誠にありがとうございます。お客様にご案内申し上げます。試着室への商品のお持込は１回、3点迄とさせて頂いております。ご理解、ご協⼒の程、宜しくお願い申し上げます。本日のご利⽤、誠にありがとうございます。",
    },
    {
      manuscript: "本⽇は、${customerName}にご来店いただきまして、誠にありがとうございます。${age}才未満、及び小中学生のお客様に御案内申し上げます。風営法により、保護者同伴なしの${age}才未満のお客様は、${time}を過ぎてのご⼊場、ご遊戯をお断りさせて頂いております。只今、${time}となりました。${age}未満及び小中学生のお客様は、どうぞご理解頂きます様、宜しくお願い申し上げます。本⽇のご来店、誠にありがとうございます。",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "22:00",
      percentage: 50,
      count: 3,
      endYearDate: "12/30",
      newYearDate: "",
      age: 18,
      minutes: 10,
      point: 100,
      expected: "本⽇は、ユーセンカフェにご来店いただきまして、誠にありがとうございます。18才未満、及び小中学生のお客様に御案内申し上げます。風営法により、保護者同伴なしの18才未満のお客様は、午後10時を過ぎてのご⼊場、ご遊戯をお断りさせて頂いております。只今、午後10時となりました。18未満及び小中学生のお客様は、どうぞご理解頂きます様、宜しくお願い申し上げます。本⽇のご来店、誠にありがとうございます。",
    },
    {
      manuscript: "本日は、${customerName}にご来店いただきまして、誠にありがとうございます。お客様にご案内申し上げます。当店は、新年1月${date2}日より営業させていただきます。皆様のご来店を⼼よりお待ちしております。本日は、ご来店ありがとうございます。引き続き、お買い物をお楽しみください。",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "22:00",
      percentage: 50,
      count: 3,
      endYearDate: "12/30",
      newYearDate: "1/2",
      age: 18,
      minutes: 10,
      point: 100,
      expected: "本日は、ユーセンカフェにご来店いただきまして、誠にありがとうございます。お客様にご案内申し上げます。当店は、新年1月2日より営業させていただきます。皆様のご来店を⼼よりお待ちしております。本日は、ご来店ありがとうございます。引き続き、お買い物をお楽しみください。",
    },
    {
      manuscript: "本日は、${customerName}にご来店いただきまして、誠にありがとうございます。当店は、本日ポイント${points}倍デー！！ご利⽤⾦額に応じてもらえるポイントが、なんと通常の${points}倍となっております！このお得な機会を、ぜひお⾒逃しなく。また、まだ会員でないお客様は、ぜひこの機会にポイントカードにご入会ください。詳しくは、係員スタッフまでお気軽にお問い合わせください。本日、ポイント${points}倍デー！！是非、この機会をご利⽤下さい！",
      lang: "ja",
      customerName: "ユーセンカフェ",
      time: "22:00",
      percentage: 50,
      count: 3,
      endYearDate: "12/30",
      newYearDate: "1/2",
      age: 18,
      minutes: 10,
      point: 5,
      expected: "本日は、ユーセンカフェにご来店いただきまして、誠にありがとうございます。当店は、本日ポイント5倍デー！！ご利⽤⾦額に応じてもらえるポイントが、なんと通常の5倍となっております！このお得な機会を、ぜひお⾒逃しなく。また、まだ会員でないお客様は、ぜひこの機会にポイントカードにご入会ください。詳しくは、係員スタッフまでお気軽にお問い合わせください。本日、ポイント5倍デー！！是非、この機会をご利⽤下さい！",
    },
  ];
  datas.forEach((v) => {
    test(`各国の原稿が正しく変換されて返ること(${v.expected.slice(0, 30)}...)`, () => {
      expect(ttsTextConverter.convertManuscript(
        v.manuscript,
        v.lang,
        v.customerName,
        v.time,
        v.percentage,
        v.count,
        v.endYearDate,
        v.newYearDate,
        v.age,
        v.minutes,
        v.point
      )).toBe(v.expected);
    });
  });
});
