/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CmMaterialListItemEndChime
 */
export interface CmMaterialListItemEndChime {
    /**
     * チャイムID
     * @type {string}
     * @memberof CmMaterialListItemEndChime
     */
    contentsId?: any;
    /**
     * ボリューム値
     * @type {number}
     * @memberof CmMaterialListItemEndChime
     */
    volume?: any;
}
