/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IndustryItem
 */
export interface IndustryItem {
    /**
     * 業種CD
     * @type {string}
     * @memberof IndustryItem
     */
    industryCd?: any;
    /**
     * 業種名
     * @type {string}
     * @memberof IndustryItem
     */
    industryName?: any;
}
