/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * UNIS顧客CD
     * @type {string}
     * @memberof User
     */
    unisCustomerCd?: any;
    /**
     * 契約CD
     * @type {string}
     * @memberof User
     */
    contractCd?: any;
    /**
     * サービスCD
     * @type {string}
     * @memberof User
     */
    serviceCd?: any;
    /**
     * サービス名
     * @type {string}
     * @memberof User
     */
    serviceName?: any;
    /**
     * 顧客名
     * @type {string}
     * @memberof User
     */
    customerName?: any;
    /**
     * 顧客名カナ
     * @type {string}
     * @memberof User
     */
    customerNameKana?: any;
    /**
     * グループCD
     * @type {string}
     * @memberof User
     */
    customerGroupCd?: any;
    /**
     * グループ名
     * @type {string}
     * @memberof User
     */
    customerGroupName?: any;
    /**
     * 契約ステータス
     * @type {string}
     * @memberof User
     */
    contractStatusCd?: any;
    /**
     * 契約ステータス名
     * @type {string}
     * @memberof User
     */
    contractStatusName?: any;
    /**
     * 登録日
     * @type {string}
     * @memberof User
     */
    createDate?: any;
    /**
     * 更新日
     * @type {string}
     * @memberof User
     */
    renewalDate?: any;
}
