/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BgmItem } from '../models';
import { ChimeItem } from '../models';
import { NarrationItem } from '../models';
import { WordItem } from '../models';
/**
 * ResourcesApi - axios parameter creator
 * @export
 */
export const ResourcesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary BGM
         * @param {string} [industryId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBgm: async (industryId?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/bgm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (industryId !== undefined) {
                localVarQueryParameter['industryId'] = industryId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Open/Endチャイム
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChime: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/chime`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ナレーション
         * @param {string} [industryId] ID of bgm to return
         * @param {string} [sceneId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNarration: async (industryId?: string, sceneId?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/narration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (industryId !== undefined) {
                localVarQueryParameter['industryId'] = industryId;
            }

            if (sceneId !== undefined) {
                localVarQueryParameter['sceneId'] = sceneId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary TTSテンプレート一覧
         * @param {string} [industryId] ID of bgm to return
         * @param {string} [sceneId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTts: async (industryId?: string, sceneId?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/tts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (industryId !== undefined) {
                localVarQueryParameter['industryId'] = industryId;
            }

            if (sceneId !== undefined) {
                localVarQueryParameter['sceneId'] = sceneId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResourcesApi - functional programming interface
 * @export
 */
export const ResourcesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary BGM
         * @param {string} [industryId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBgm(industryId?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BgmItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listBgm(industryId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Open/Endチャイム
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChime(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ChimeItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listChime(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary ナレーション
         * @param {string} [industryId] ID of bgm to return
         * @param {string} [sceneId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listNarration(industryId?: string, sceneId?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NarrationItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listNarration(industryId, sceneId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary TTSテンプレート一覧
         * @param {string} [industryId] ID of bgm to return
         * @param {string} [sceneId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTts(industryId?: string, sceneId?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WordItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listTts(industryId, sceneId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ResourcesApi - factory interface
 * @export
 */
export const ResourcesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary BGM
         * @param {string} [industryId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBgm(industryId?: string, options?: any): AxiosPromise<Array<BgmItem>> {
            return ResourcesApiFp(configuration).listBgm(industryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Open/Endチャイム
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChime(options?: any): AxiosPromise<Array<ChimeItem>> {
            return ResourcesApiFp(configuration).listChime(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ナレーション
         * @param {string} [industryId] ID of bgm to return
         * @param {string} [sceneId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNarration(industryId?: string, sceneId?: string, options?: any): AxiosPromise<Array<NarrationItem>> {
            return ResourcesApiFp(configuration).listNarration(industryId, sceneId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary TTSテンプレート一覧
         * @param {string} [industryId] ID of bgm to return
         * @param {string} [sceneId] ID of bgm to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTts(industryId?: string, sceneId?: string, options?: any): AxiosPromise<Array<WordItem>> {
            return ResourcesApiFp(configuration).listTts(industryId, sceneId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ResourcesApi - object-oriented interface
 * @export
 * @class ResourcesApi
 * @extends {BaseAPI}
 */
export class ResourcesApi extends BaseAPI {
    /**
     * 
     * @summary BGM
     * @param {string} [industryId] ID of bgm to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listBgm(industryId?: string, options?: any) {
        return ResourcesApiFp(this.configuration).listBgm(industryId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Open/Endチャイム
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listChime(options?: any) {
        return ResourcesApiFp(this.configuration).listChime(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary ナレーション
     * @param {string} [industryId] ID of bgm to return
     * @param {string} [sceneId] ID of bgm to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listNarration(industryId?: string, sceneId?: string, options?: any) {
        return ResourcesApiFp(this.configuration).listNarration(industryId, sceneId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary TTSテンプレート一覧
     * @param {string} [industryId] ID of bgm to return
     * @param {string} [sceneId] ID of bgm to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listTts(industryId?: string, sceneId?: string, options?: any) {
        return ResourcesApiFp(this.configuration).listTts(industryId, sceneId, options).then((request) => request(this.axios, this.basePath));
    }
}
