/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BgmItem } from '../models';
import { ChimeItem } from '../models';
import { InlineResponse200 } from '../models';
import { NarrationItem } from '../models';
import { WordItem } from '../models';
/**
 * ResourcesApi - axios parameter creator
 * @export
 */
export const ResourcesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 試聴再生、音声素材アップロードのURLを取得する
         * @summary S3オブジェクトの署名付きURLの取得
         * @param {string} id 音源ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSignedUrl: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getSignedUrl.');
            }
            const localVarPath = `/signedUrl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * BGM素材を一覧で取得する
         * @summary BGM
         * @param {string} [industryCd] 業種CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBgm: async (industryCd?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/bgm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (industryCd !== undefined) {
                localVarQueryParameter['industryCd'] = industryCd;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 開始/終了チャイムを一覧で取得する
         * @summary Open/Endチャイム
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChime: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/chime`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * ナレーション素材を一覧で取得する
         * @summary ナレーション
         * @param {string} [industryCd] 業種CD
         * @param {string} [sceneCd] シーンCD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNarration: async (industryCd?: string, sceneCd?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/narration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (industryCd !== undefined) {
                localVarQueryParameter['industryCd'] = industryCd;
            }

            if (sceneCd !== undefined) {
                localVarQueryParameter['sceneCd'] = sceneCd;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * TTSのテンプレート素材を一覧で取得する
         * @summary TTSテンプレート一覧
         * @param {string} [industryCd] 業種CD
         * @param {string} [sceneCd] シーンCD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTts: async (industryCd?: string, sceneCd?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/tts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (industryCd !== undefined) {
                localVarQueryParameter['industryCd'] = industryCd;
            }

            if (sceneCd !== undefined) {
                localVarQueryParameter['sceneCd'] = sceneCd;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResourcesApi - functional programming interface
 * @export
 */
export const ResourcesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 試聴再生、音声素材アップロードのURLを取得する
         * @summary S3オブジェクトの署名付きURLの取得
         * @param {string} id 音源ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSignedUrl(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).getSignedUrl(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * BGM素材を一覧で取得する
         * @summary BGM
         * @param {string} [industryCd] 業種CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBgm(industryCd?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BgmItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listBgm(industryCd, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 開始/終了チャイムを一覧で取得する
         * @summary Open/Endチャイム
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChime(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ChimeItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listChime(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * ナレーション素材を一覧で取得する
         * @summary ナレーション
         * @param {string} [industryCd] 業種CD
         * @param {string} [sceneCd] シーンCD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listNarration(industryCd?: string, sceneCd?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NarrationItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listNarration(industryCd, sceneCd, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * TTSのテンプレート素材を一覧で取得する
         * @summary TTSテンプレート一覧
         * @param {string} [industryCd] 業種CD
         * @param {string} [sceneCd] シーンCD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTts(industryCd?: string, sceneCd?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WordItem>>> {
            const localVarAxiosArgs = await ResourcesApiAxiosParamCreator(configuration).listTts(industryCd, sceneCd, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ResourcesApi - factory interface
 * @export
 */
export const ResourcesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 試聴再生、音声素材アップロードのURLを取得する
         * @summary S3オブジェクトの署名付きURLの取得
         * @param {string} id 音源ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSignedUrl(id: string, options?: any): AxiosPromise<InlineResponse200> {
            return ResourcesApiFp(configuration).getSignedUrl(id, options).then((request) => request(axios, basePath));
        },
        /**
         * BGM素材を一覧で取得する
         * @summary BGM
         * @param {string} [industryCd] 業種CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBgm(industryCd?: string, options?: any): AxiosPromise<Array<BgmItem>> {
            return ResourcesApiFp(configuration).listBgm(industryCd, options).then((request) => request(axios, basePath));
        },
        /**
         * 開始/終了チャイムを一覧で取得する
         * @summary Open/Endチャイム
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChime(options?: any): AxiosPromise<Array<ChimeItem>> {
            return ResourcesApiFp(configuration).listChime(options).then((request) => request(axios, basePath));
        },
        /**
         * ナレーション素材を一覧で取得する
         * @summary ナレーション
         * @param {string} [industryCd] 業種CD
         * @param {string} [sceneCd] シーンCD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNarration(industryCd?: string, sceneCd?: string, options?: any): AxiosPromise<Array<NarrationItem>> {
            return ResourcesApiFp(configuration).listNarration(industryCd, sceneCd, options).then((request) => request(axios, basePath));
        },
        /**
         * TTSのテンプレート素材を一覧で取得する
         * @summary TTSテンプレート一覧
         * @param {string} [industryCd] 業種CD
         * @param {string} [sceneCd] シーンCD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTts(industryCd?: string, sceneCd?: string, options?: any): AxiosPromise<Array<WordItem>> {
            return ResourcesApiFp(configuration).listTts(industryCd, sceneCd, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ResourcesApi - object-oriented interface
 * @export
 * @class ResourcesApi
 * @extends {BaseAPI}
 */
export class ResourcesApi extends BaseAPI {
    /**
     * 試聴再生、音声素材アップロードのURLを取得する
     * @summary S3オブジェクトの署名付きURLの取得
     * @param {string} id 音源ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public getSignedUrl(id: string, options?: any) {
        return ResourcesApiFp(this.configuration).getSignedUrl(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * BGM素材を一覧で取得する
     * @summary BGM
     * @param {string} [industryCd] 業種CD
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listBgm(industryCd?: string, options?: any) {
        return ResourcesApiFp(this.configuration).listBgm(industryCd, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 開始/終了チャイムを一覧で取得する
     * @summary Open/Endチャイム
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listChime(options?: any) {
        return ResourcesApiFp(this.configuration).listChime(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * ナレーション素材を一覧で取得する
     * @summary ナレーション
     * @param {string} [industryCd] 業種CD
     * @param {string} [sceneCd] シーンCD
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listNarration(industryCd?: string, sceneCd?: string, options?: any) {
        return ResourcesApiFp(this.configuration).listNarration(industryCd, sceneCd, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * TTSのテンプレート素材を一覧で取得する
     * @summary TTSテンプレート一覧
     * @param {string} [industryCd] 業種CD
     * @param {string} [sceneCd] シーンCD
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResourcesApi
     */
    public listTts(industryCd?: string, sceneCd?: string, options?: any) {
        return ResourcesApiFp(this.configuration).listTts(industryCd, sceneCd, options).then((request) => request(this.axios, this.basePath));
    }
}
