/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GenerateTtsItem } from '../models';
import { TtsItem } from '../models';
/**
 * TtsApi - axios parameter creator
 * @export
 */
export const TtsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 合成音声素材を新規登録する
         * @summary TTSデータ登録
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {any} [body] TTS登録リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserTts: async (xUnisCustomerCd: string, body?: any, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUnisCustomerCd' is not null or undefined
            if (xUnisCustomerCd === null || xUnisCustomerCd === undefined) {
                throw new RequiredError('xUnisCustomerCd','Required parameter xUnisCustomerCd was null or undefined when calling createUserTts.');
            }
            const localVarPath = `/user/tts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xUnisCustomerCd !== undefined && xUnisCustomerCd !== null) {
                localVarHeaderParameter['x-unis-customer-cd'] = String(xUnisCustomerCd);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 合成音声素材を削除する
         * @summary TTSデータ削除
         * @param {string} id 合成音声ID
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserTts: async (id: string, xUnisCustomerCd: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteUserTts.');
            }
            // verify required parameter 'xUnisCustomerCd' is not null or undefined
            if (xUnisCustomerCd === null || xUnisCustomerCd === undefined) {
                throw new RequiredError('xUnisCustomerCd','Required parameter xUnisCustomerCd was null or undefined when calling deleteUserTts.');
            }
            const localVarPath = `/user/tts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xUnisCustomerCd !== undefined && xUnisCustomerCd !== null) {
                localVarHeaderParameter['x-unis-customer-cd'] = String(xUnisCustomerCd);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 合成音声を生成する
         * @summary TTSデータ生成
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {any} [body] TTS作成リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUserTts: async (xUnisCustomerCd: string, body?: any, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUnisCustomerCd' is not null or undefined
            if (xUnisCustomerCd === null || xUnisCustomerCd === undefined) {
                throw new RequiredError('xUnisCustomerCd','Required parameter xUnisCustomerCd was null or undefined when calling generateUserTts.');
            }
            const localVarPath = `/user/tts/generate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xUnisCustomerCd !== undefined && xUnisCustomerCd !== null) {
                localVarHeaderParameter['x-unis-customer-cd'] = String(xUnisCustomerCd);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 合成音声素材の情報を取得する
         * @summary TTSデータ取得
         * @param {string} id 合成音声ID
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTts: async (id: string, xUnisCustomerCd: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getUserTts.');
            }
            // verify required parameter 'xUnisCustomerCd' is not null or undefined
            if (xUnisCustomerCd === null || xUnisCustomerCd === undefined) {
                throw new RequiredError('xUnisCustomerCd','Required parameter xUnisCustomerCd was null or undefined when calling getUserTts.');
            }
            const localVarPath = `/user/tts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xUnisCustomerCd !== undefined && xUnisCustomerCd !== null) {
                localVarHeaderParameter['x-unis-customer-cd'] = String(xUnisCustomerCd);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 合成音声素材の情報を一覧で取得する
         * @summary TTSデータ一覧取得
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {number} [sort] ソート (1：title昇順, 2：title降順, 3：timestamp昇順, 4：timestamp降順)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUserTts: async (xUnisCustomerCd: string, sort?: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUnisCustomerCd' is not null or undefined
            if (xUnisCustomerCd === null || xUnisCustomerCd === undefined) {
                throw new RequiredError('xUnisCustomerCd','Required parameter xUnisCustomerCd was null or undefined when calling listUserTts.');
            }
            const localVarPath = `/user/tts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (xUnisCustomerCd !== undefined && xUnisCustomerCd !== null) {
                localVarHeaderParameter['x-unis-customer-cd'] = String(xUnisCustomerCd);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 合成音声素材の情報を更新する
         * @summary TTSデータ更新（メタデータのみ）
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {string} id 合成音声ID
         * @param {any} [body] ユーザー素材データ更新リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserTts: async (xUnisCustomerCd: string, id: string, body?: any, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUnisCustomerCd' is not null or undefined
            if (xUnisCustomerCd === null || xUnisCustomerCd === undefined) {
                throw new RequiredError('xUnisCustomerCd','Required parameter xUnisCustomerCd was null or undefined when calling updateUserTts.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling updateUserTts.');
            }
            const localVarPath = `/user/tts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (xUnisCustomerCd !== undefined && xUnisCustomerCd !== null) {
                localVarHeaderParameter['x-unis-customer-cd'] = String(xUnisCustomerCd);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TtsApi - functional programming interface
 * @export
 */
export const TtsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 合成音声素材を新規登録する
         * @summary TTSデータ登録
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {any} [body] TTS登録リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserTts(xUnisCustomerCd: string, body?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TtsItem>>> {
            const localVarAxiosArgs = await TtsApiAxiosParamCreator(configuration).createUserTts(xUnisCustomerCd, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 合成音声素材を削除する
         * @summary TTSデータ削除
         * @param {string} id 合成音声ID
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUserTts(id: string, xUnisCustomerCd: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TtsItem>> {
            const localVarAxiosArgs = await TtsApiAxiosParamCreator(configuration).deleteUserTts(id, xUnisCustomerCd, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 合成音声を生成する
         * @summary TTSデータ生成
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {any} [body] TTS作成リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateUserTts(xUnisCustomerCd: string, body?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenerateTtsItem>> {
            const localVarAxiosArgs = await TtsApiAxiosParamCreator(configuration).generateUserTts(xUnisCustomerCd, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 合成音声素材の情報を取得する
         * @summary TTSデータ取得
         * @param {string} id 合成音声ID
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTts(id: string, xUnisCustomerCd: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TtsItem>> {
            const localVarAxiosArgs = await TtsApiAxiosParamCreator(configuration).getUserTts(id, xUnisCustomerCd, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 合成音声素材の情報を一覧で取得する
         * @summary TTSデータ一覧取得
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {number} [sort] ソート (1：title昇順, 2：title降順, 3：timestamp昇順, 4：timestamp降順)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUserTts(xUnisCustomerCd: string, sort?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TtsItem>>> {
            const localVarAxiosArgs = await TtsApiAxiosParamCreator(configuration).listUserTts(xUnisCustomerCd, sort, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 合成音声素材の情報を更新する
         * @summary TTSデータ更新（メタデータのみ）
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {string} id 合成音声ID
         * @param {any} [body] ユーザー素材データ更新リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserTts(xUnisCustomerCd: string, id: string, body?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TtsItem>> {
            const localVarAxiosArgs = await TtsApiAxiosParamCreator(configuration).updateUserTts(xUnisCustomerCd, id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TtsApi - factory interface
 * @export
 */
export const TtsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 合成音声素材を新規登録する
         * @summary TTSデータ登録
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {any} [body] TTS登録リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserTts(xUnisCustomerCd: string, body?: any, options?: any): AxiosPromise<Array<TtsItem>> {
            return TtsApiFp(configuration).createUserTts(xUnisCustomerCd, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 合成音声素材を削除する
         * @summary TTSデータ削除
         * @param {string} id 合成音声ID
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserTts(id: string, xUnisCustomerCd: string, options?: any): AxiosPromise<TtsItem> {
            return TtsApiFp(configuration).deleteUserTts(id, xUnisCustomerCd, options).then((request) => request(axios, basePath));
        },
        /**
         * 合成音声を生成する
         * @summary TTSデータ生成
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {any} [body] TTS作成リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateUserTts(xUnisCustomerCd: string, body?: any, options?: any): AxiosPromise<GenerateTtsItem> {
            return TtsApiFp(configuration).generateUserTts(xUnisCustomerCd, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 合成音声素材の情報を取得する
         * @summary TTSデータ取得
         * @param {string} id 合成音声ID
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTts(id: string, xUnisCustomerCd: string, options?: any): AxiosPromise<TtsItem> {
            return TtsApiFp(configuration).getUserTts(id, xUnisCustomerCd, options).then((request) => request(axios, basePath));
        },
        /**
         * 合成音声素材の情報を一覧で取得する
         * @summary TTSデータ一覧取得
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {number} [sort] ソート (1：title昇順, 2：title降順, 3：timestamp昇順, 4：timestamp降順)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUserTts(xUnisCustomerCd: string, sort?: number, options?: any): AxiosPromise<Array<TtsItem>> {
            return TtsApiFp(configuration).listUserTts(xUnisCustomerCd, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 合成音声素材の情報を更新する
         * @summary TTSデータ更新（メタデータのみ）
         * @param {string} xUnisCustomerCd UNIS顧客CD
         * @param {string} id 合成音声ID
         * @param {any} [body] ユーザー素材データ更新リクエストBody
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserTts(xUnisCustomerCd: string, id: string, body?: any, options?: any): AxiosPromise<TtsItem> {
            return TtsApiFp(configuration).updateUserTts(xUnisCustomerCd, id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TtsApi - object-oriented interface
 * @export
 * @class TtsApi
 * @extends {BaseAPI}
 */
export class TtsApi extends BaseAPI {
    /**
     * 合成音声素材を新規登録する
     * @summary TTSデータ登録
     * @param {string} xUnisCustomerCd UNIS顧客CD
     * @param {any} [body] TTS登録リクエストBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TtsApi
     */
    public createUserTts(xUnisCustomerCd: string, body?: any, options?: any) {
        return TtsApiFp(this.configuration).createUserTts(xUnisCustomerCd, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 合成音声素材を削除する
     * @summary TTSデータ削除
     * @param {string} id 合成音声ID
     * @param {string} xUnisCustomerCd UNIS顧客CD
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TtsApi
     */
    public deleteUserTts(id: string, xUnisCustomerCd: string, options?: any) {
        return TtsApiFp(this.configuration).deleteUserTts(id, xUnisCustomerCd, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 合成音声を生成する
     * @summary TTSデータ生成
     * @param {string} xUnisCustomerCd UNIS顧客CD
     * @param {any} [body] TTS作成リクエストBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TtsApi
     */
    public generateUserTts(xUnisCustomerCd: string, body?: any, options?: any) {
        return TtsApiFp(this.configuration).generateUserTts(xUnisCustomerCd, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 合成音声素材の情報を取得する
     * @summary TTSデータ取得
     * @param {string} id 合成音声ID
     * @param {string} xUnisCustomerCd UNIS顧客CD
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TtsApi
     */
    public getUserTts(id: string, xUnisCustomerCd: string, options?: any) {
        return TtsApiFp(this.configuration).getUserTts(id, xUnisCustomerCd, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 合成音声素材の情報を一覧で取得する
     * @summary TTSデータ一覧取得
     * @param {string} xUnisCustomerCd UNIS顧客CD
     * @param {number} [sort] ソート (1：title昇順, 2：title降順, 3：timestamp昇順, 4：timestamp降順)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TtsApi
     */
    public listUserTts(xUnisCustomerCd: string, sort?: number, options?: any) {
        return TtsApiFp(this.configuration).listUserTts(xUnisCustomerCd, sort, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 合成音声素材の情報を更新する
     * @summary TTSデータ更新（メタデータのみ）
     * @param {string} xUnisCustomerCd UNIS顧客CD
     * @param {string} id 合成音声ID
     * @param {any} [body] ユーザー素材データ更新リクエストBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TtsApi
     */
    public updateUserTts(xUnisCustomerCd: string, id: string, body?: any, options?: any) {
        return TtsApiFp(this.configuration).updateUserTts(xUnisCustomerCd, id, body, options).then((request) => request(this.axios, this.basePath));
    }
}
