openapi: 3.0.0
info:
  title: U-Messe API
  description: U-Messe API
  version: 0.0.1
servers:
- url: /api
paths:
  /ping:
    get:
      tags:
      - ping
      summary: ping
      operationId: pingGET
      responses:
        default:
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
      x-swagger-router-controller: Ping
  /auth:
    post:
      tags:
      - auth
      summary: 端末認証
      operationId: authPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "200":
          description: 端末認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
      x-swagger-router-controller: Auth
  /user:
    get:
      tags:
      - user
      summary: User情報取得
      operationId: userGET
      responses:
        "200":
          description: User情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: User
  /user/cm:
    get:
      tags:
      - cm
      summary: CMリスト取得
      operationId: userCmGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CMItem'
                x-content-type: application/json
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Cm
    post:
      tags:
      - cm
      summary: CM新規追加
      operationId: userCmPOST
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CMItem'
        default:
          description: Default error sample response
      x-swagger-router-controller: Cm
  /cm/{cmId}:
    post:
      tags:
      - cm
      summary: CM情報更新
      operationId: cmCmIdPOST
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Cm
    delete:
      tags:
      - cm
      summary: cm 削除
      operationId: cmCmIdDELETE
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Cm
  /user/recording:
    get:
      tags:
      - recording
      summary: 録音データリスト取得
      operationId: userRecordingGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Recording
    post:
      tags:
      - recording
      summary: 新規録音データ
      operationId: userRecordingPOST
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_1'
      responses:
        "200":
          description: successful
      x-swagger-router-controller: Recording
  /user/recording/{recordingId}:
    get:
      tags:
      - recording
      summary: 録音データ取得
      operationId: userRecordingRecordingIdGET
      parameters:
      - name: recordingId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Recording
    delete:
      tags:
      - recording
      summary: 録音データ削除
      operationId: userRecordingRecordingIdDELETE
      parameters:
      - name: recordingId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Recording
  /user/tts:
    get:
      tags:
      - tts
      summary: TTSデータリスト取得
      operationId: userTtsGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-swagger-router-controller: Tts
    post:
      tags:
      - tts
      summary: 新規録音データ
      operationId: userTtsPOST
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_2'
      responses:
        "200":
          description: successful
      x-swagger-router-controller: Tts
  /user/tts/{ttsId}:
    get:
      tags:
      - tts
      summary: TTSデータ取得
      operationId: userTtsTtsIdGET
      parameters:
      - name: ttsId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Tts
    delete:
      tags:
      - tts
      summary: TTSデータ削除
      operationId: userTtsTtsIdDELETE
      parameters:
      - name: ttsId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Tts
  /bgm:
    get:
      tags:
      - resources
      summary: BGM
      operationId: bgmGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /narration:
    get:
      tags:
      - resources
      summary: ナレーションリスト取得
      operationId: narrationGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrationListItem'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /narration/{sceneId}:
    get:
      tags:
      - resources
      summary: ナレーション取得
      operationId: narrationSceneIdGET
      parameters:
      - name: sceneId
        in: path
        description: ID of narration to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrationSceneListItem'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /chime:
    get:
      tags:
      - resources
      summary: Open/Endチャイム
      operationId: chimeGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /tts:
    get:
      tags:
      - resources
      summary: TTSテンプレート一覧
      operationId: ttsGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
components:
  schemas:
    Auth:
      properties:
        token:
          type: string
          example: "1234567890"
      example:
        token: "1234567890"
    User:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: Meguro Cafe
      example:
        name: Meguro Cafe
        id: 1234
    CMItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    BGMItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    NarrationListItem:
      type: array
      example:
      - id: 1
        name: 業種名1
        scenes:
        - id: 11
          name: シーン名11
        - id: 12
          name: シーン名12
        - id: 13
          name: シーン名13
      - id: 2
        name: 業種名2
        scenes:
        - id: 21
          name: シーン名21
        - id: 22
          name: シーン名22
        - id: 23
          name: シーン名23
      - id: 3
        name: 業種名3
        scenes:
        - id: 31
          name: シーン名31
        - id: 32
          name: シーン名32
        - id: 33
          name: シーン名33
      items:
        $ref: '#/components/schemas/IndustryItem'
    IndustryItem:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 業種名
        scenes:
          type: array
          items:
            $ref: '#/components/schemas/SceneItem'
    SceneItem:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: シーン名
    NarrationSceneListItem:
      type: array
      example:
      - id: 1
        name: 18時30分閉店
        detail: 放送開始日2020年10月15日 有効期限2020年10月20日
        manuscript: 本日はご来店いただきましてありがとうございます。当店は18時30分閉店です
        second: 10
        url: https://example.com
      - id: 2
        name: アルバイト募集
        detail: 放送開始日2020年10月15日 有効期限2020年10月20日
        manuscript: 当店ではアルバイトを募集しております。なんたらかんたら
        second: 20
        url: https://example.com
      - id: 3
        name: チャイルドチェア
        detail: 放送開始日2020年10月15日 有効期限2020年10月20日
        manuscript: 本日はご来店いただきましてありがとうございます。なんたらかんたら
        second: 30
        url: https://example.com
      - id: 4
        name: デリバリー
        detail: 放送開始日2020年10月15日 有効期限2020年10月20日
        manuscript: 本日はご来店いただきましてありがとうございます。なんたらかんたら
        second: 40
        url: https://example.com
      items:
        $ref: '#/components/schemas/NarrationItem'
    NarrationItem:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 18時30分閉店
        detail:
          type: string
          example: 放送開始日2020年10月15日 有効期限2020年10月20日
        manuscript:
          type: string
          example: 本日はご来店いただきましてありがとうございます。当店は18時30分閉店です
        url:
          type: string
          description: 試聴URL
          example: https://example.com
        second:
          type: integer
          example: 30
    ChimeItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    RecordingItem:
      properties:
        id:
          type: integer
        title:
          type: string
        detail:
          type: string
      example:
        id: 0
        detail: detail
        title: title
    Error:
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string
      description: Error
    inline_response_default:
      properties:
        message:
          type: string
          example: ok
      example:
        message: ok
    body:
      type: object
      properties:
        unis_customer_cd:
          type: string
    inline_response_200:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/RecordingItem'
      example:
        data:
        - id: 0
          detail: detail
          title: title
        - id: 0
          detail: detail
          title: title
        value: value
    body_1:
      type: object
      properties:
        filename:
          type: string
        recordedFile:
          type: string
          format: binary
    inline_response_200_1:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/TtsItem'
      example:
        data:
        - '{}'
        - '{}'
        value: value
    body_2:
      type: object
      properties:
        filename:
          type: string
        recordedFile:
          type: string
          format: binary
    inline_response_200_2:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/BGMItem'
      example:
        data:
        - name: name
          id: 0
          detail: detail
        - name: name
          id: 0
          detail: detail
        value: value
    inline_response_200_3:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/ChimeItem'
      example:
        data:
        - name: name
          id: 0
          detail: detail
        - name: name
          id: 0
          detail: detail
        value: value
