version: '3'
services:
  local-storage:
    container_name: local-storage
    hostname: local-storage
    image: minio/minio
    volumes:
      - ./storage:/storage
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: 1234567890
      MINIO_SECRET_KEY: 1234567890
    command: server /storage
    networks:
      - default

  local-dynamodb:
    container_name: local-dynamodb
    hostname: local-dynamodb
    image: amazon/dynamodb-local
    volumes:
      - ./dynamodb:/home/dynamodblocal
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data -optimizeDbBeforeStartup
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: 1234567890
      AWS_SECRET_ACCESS_KEY: 1234567890
    networks:
      - default

  # local-swagger:
  #   container_name: local-swagger
  #   hostname: local-swagger
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./lambda/swagger.yaml:/usr/share/nginx/html/swagger.yaml
  #   environment:
  #     API_URL: swagger.yaml
  #   networks:
  #     - default

  local-webapp:
    container_name: local-webapp
    hostname: local-webapp
    build: ./
    tty: true
    ports:
      - 3001:3001
    volumes:
      - ./webapp:/webapp
    networks:
      - default
