version: '3'
services:

  locallambda:
    container_name: locallambda
    hostname: locallambda
    image: lambci/lambda:nodejs12.x
    volumes:
      - ./lambda:/var/task
    ports:
      - 9001:9001
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCOUNT_ID: local
      DOCKER_LAMBDA_WATCH: 1
      DOCKER_LAMBDA_STAY_OPEN: 1
    command: index.handler
    links:
      - localstack
    depends_on:
      - localstack
    networks:
      - default

  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack
    volumes:
      - ./storage:/var/localstack/storage
    ports:
      - 8080:8080
      - 4572:4572
    environment:
      SERVICES: s3
      DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /var/localstack/storage
    command: cd /var/localstack/storage && ./buckets.sh
    networks:
      - default
