swagger: '2.0'
info:
  version: 0.0.1
  title: U-Messe API
  description: サンプル
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /list:
    post:
      tags:
        - list
      summary: ファイルリスト取得
      description: S3からファイルリストを取得する
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: bucket
          schema:
            type: object
            properties:
              bucket:
                type: string
                example: umesse-contents
              key:
                type: string
                example: BGM
      responses:
        200:
          description: OK
        400:
          description: Bad request
        500:
          description: Internal server error
