@startuml s2-1

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 2-1 CM一覧取得 **

== CM一覧取得 ==
WebApp --> Lambda: リスト取得
Lambda --> S3: リスト取得(listObjectsV2)
note right
// CMのMetadata
{
  "Metadata": {
    "start-chime": "ファイル名",
    "start-chime-volume": "1.0",
    "end-chime": "ファイル名",
    "end-chime-volume": "1.0",
    "bgm": "ファイル名",
    "bgm-volume": "1.0",
    "narration-1": "ファイル名",
    "narration-1-volume": "1.0",
    "narration-2": "ファイル名",
    "narration-2-volume": "1.0",
    "narration-3": "ファイル名",
    "narration-3-volume": "1.0",
    "narration-4": "ファイル名",
    "narration-4-volume": "1.0",
    "shared-path": "シェアファイルパス",
    "center-enabled": "true",
  }
}
end note
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス
WebApp --> WebApp: ソート（更新日・名称）

@enduml