@startuml s2-1

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 2-1 CMリスト取得 **

== CMリスト取得 ==
WebApp --> Lambda: リスト取得
Lambda --> DynamoDB: リスト取得
note right
{
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  seconds: {I, '秒数'},
  start_date: {S, '2014-10-10T13:50:40+09:00'},
  end_date: {S, '9999-12-31T23:59:59+09:00'},
  production_type: {S, '01: 音楽系, 02: 素ナレ'},
  industry: {S: '業種名'},
  scene: {S: 'シーン名'},
  materials: {
    narrations: [
      {
        id: {S, 'ファイル名'},
        volume: {I, 'ボリューム値'},
      }
    ],
    start_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    end_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    bgm: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
  },
  status: {S: 'CMステータス'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス
WebApp --> WebApp: ソート（作成日・タイトル名）

@enduml