@startuml s2-3

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 2-3 CM共有・解除 **

== CM共有 ==
WebApp --> Lambda: CM共有
Lambda --> DynamoDB: ユーザー情報取得（グループID）
Lambda <-- DynamoDB: レスポンス
Lambda --> S3: CMコピー(copyObject)
S3 --> S3: CMコピー(umesse-users/グループID/cm/ 配下へ)
Lambda <-- S3: レスポンス
Lambda --> DynamoDB: CMメタデータ更新
note right
{
  Id: {S, 'ファイル名'},
  GroupShear: ture,
  TimeStamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== CM共有解除 ==
WebApp --> Lambda: CM共有解除
Lambda --> DynamoDB: ユーザー情報取得（グループID）
Lambda <-- DynamoDB: レスポンス
Lambda --> S3: CM削除(deleteObject)
S3 --> S3: CM削除(umesse-users/グループID/cm/ 配下削除)
Lambda <-- S3: レスポンス
Lambda --> DynamoDB: CMメタデータ更新
note right
{
  Id: {S, 'ファイル名'},
  GroupShear: false,
  TimeStamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

@enduml