@startuml s2-3

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 2-3 CM共有・解除 **

== CM一覧取得 ==
WebApp --> Lambda: リスト取得
Lambda --> S3: リスト取得(listObjectsV2)
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス

== CM共有 ==
WebApp --> Lambda: CM共有
Lambda --> DynamoDB: ユーザー情報取得（グループID）U MEMBERS
Lambda <-- DynamoDB: レスポンス
Lambda --> S3: CMコピー(copyObject)
S3 --> S3: CMコピー(umesse-users/グループID/CM/ 配下へ)
Lambda <-- S3: レスポンス
Lambda --> S3: CMメタ更新(copyObject)
S3 --> S3: CMメタ更新
note right
// CMのMetadata
{
  "Metadata": {
    "start-chime": "ファイル名",
    "start-chime-volume": "1.0",
    "end-chime": "ファイル名",
    "end-chime-volume": "1.0",
    "bgm": "ファイル名",
    "bgm-volume": "1.0",
    "narration-1": "ファイル名",
    "narration-1-volume": "1.0",
    "shared-path": "シェアファイルパス",
  }
}
end note
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス

== CM共有解除 ==
WebApp --> Lambda: CM共有解除
Lambda --> DynamoDB: ユーザー情報取得（グループID）U MEMBERS
Lambda <-- DynamoDB: レスポンス
Lambda --> S3: CM削除(deleteObject)
S3 --> S3: CM削除(umesse-users/グループID/CM/ 配下削除)
Lambda <-- S3: レスポンス
Lambda --> S3: CMメタ更新(copyObject)
S3 --> S3: CMメタ更新
note right
// CMのMetadata
{
  "Metadata": {
    "start-chime": "ファイル名",
    "start-chime-volume": "1.0",
    "end-chime": "ファイル名",
    "end-chime-volume": "1.0",
    "bgm": "ファイル名",
    "bgm-volume": "1.0",
    "narration-1": "ファイル名",
    "narration-1-volume": "1.0",
  }
}
end note
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス

@enduml