@startuml s2-5

participant Center order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 2-5 CMセンター連携 **

== CMセンター連携 ==
Center --> Lambda: CM連携リスト取得
Lambda --> DynamoDB: データ取得（センター連携用）
note right
{
  unisCustomerCd: {S, '顧客CD'},
  dataProcessType: {S, '01: 追加, 02: 変更, 03: 削除'}
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  seconds: {I, '秒数'},
  startDate: {S, '2014-10-10T13:50:40+09:00'},
  endDate: {S, '9999-12-31T23:59:59+09:00'},
  productionType: {S, '01: 音楽系, 02: 素ナレ'},
  industry: {S: '業種名'},
  scene: {S: 'シーン名'},
  status: {I, '1: 連携可能}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
Lambda --> S3: 追加の場合、signed url 取得(getSignedUrl)
Lambda <-- S3: signed url
Center <-- Lambda: レスポンス
note right
{
  "unisCustomerCd" : "12345",
  "cmMetas" : [
    {
      "dataProcessType" : "01",
      "uMesseCmCd" : "0999999900-c-sfja8eo1",
      "url" : "https://xxxxx/0999999900-c-sfja8eo1.aac?AWSAccessKeyId=xxxxxxxx",
      "cmName" : "時報A",
      "cmCommentManuscript" : "テストCMです",
      "startDatetime" : "2020-01-01T12:34:56+09:00",
      "endDatetime" : "9999-12-31T23:59:59+09:00",
      "productionType" : "01",
      "fileName" : "0999999900-c-sfja8eo1.aac",
      "contentTime" : 30000,
      "fileSize" : 1234567,
      "sceneCd" : "001",
    }
  ]
}
end note

== CMセンター連携完了 ==
Center --> Lambda: CM連携完了
Lambda --> DynamoDB: データ削除（センター連携用）
DynamoDB --> DynamoDB: 該当データ削除
Lambda <-- DynamoDB: レスポンス
Lambda --> DynamoDB: データ更新（CMメタデータ）
note right
{
  id: {S, 'ファイル名'},
  status: {S: '12: センターアップロード完了'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
Center <-- Lambda: レスポンス

== CMセンター連携エラー ==
Center --> Lambda: CM連携エラー
Lambda --> DynamoDB: データ更新（センター連携用）
note right
{
  unisCustomerCd: {S, '顧客CD'},
  id: {S, 'ファイル名'},
  status: {I, '9: 連携失敗},
  errorCode: {S, 'エラーコード'},
  errorMessage: {S, 'エラーメッセージ'},
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
Lambda --> DynamoDB: データ更新（CMメタデータ）
note right
{
  id: {S, 'ファイル名'},
  status: {S: '19: センターアップロード失敗'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
Center <-- Lambda: レスポンス


@enduml