@startuml s3-1

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 3-1 CM作成 **

== CM新規作成・編集 ==
WebApp --> Lambda: CM新規作成・編集
Lambda --> DynamoDB: CMデータ取得
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== 音源一覧取得 ==
WebApp --> Lambda: リスト取得（ナレーション・チャイム・BGM・オリジナル）
Lambda --> S3: リスト取得
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス

== 編集（リアルタイム更新） ==
WebApp --> Lambda: 編集
note right
// draft
{
  "cm_id": "CMファイル名(タイトル.aac 重複不可)",
  "cm_tag": [
    "ランチ",
    "セール",
  ],
  "start_chime": {
    "id": "(chime_id or file_name)",
    "volume": "1.0",
  },
  "end_chime": {
    "id": "(chime_id or file_name)",
    "volume": "1.0",
  },
  "bgm": {
    "id": "(bgm_id or file_name)",
    "volume": "1.0",
  },
  "narrations": [
    {
      "id": "(narration_id or file_name)",
      "volume": "1.0",
    },
    {
      "id": "(narration_id or file_name)",
      "volume": "1.0",
    },
  ],
  "timestamp": "timestamp",
}
end note
Lambda --> DynamoDB: CMデータ更新
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== 結合 ==
WebApp --> Lambda: 確定
Lambda --> DynamoDB: CMデータ取得
Lambda <-- DynamoDB: レスポンス
Lambda --> S3: 該当ファイル取得
Lambda <-- S3: ファイル取得
Lambda --> Lambda: ffmpeg 結合
Lambda --> S3: ファイルPUT
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス

@enduml