@startuml s3-2

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
participant SQS order 5
skinparam ParticipantPadding 50
autonumber

title ** 3-2 CM変更・削除 **

== CM編集 ==
WebApp --> Lambda: CMデータ取得
Lambda --> DynamoDB: データ取得
note right
{
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  seconds: {I, '秒数'},
  start_date: {S, '2014-10-10T13:50:40+09:00'},
  end_date: {S, '9999-12-31T23:59:59+09:00'},
  production_type: {S, '01: 音楽系, 02: 素ナレ'},
  industry: {S: '業種名'},
  scene: {S: 'シーン名'},
  materials: {
    narrations: [
      {
        id: {S, 'ファイル名'},
        volume: {I, 'ボリューム値'},
      }
    ],
    start_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    end_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    bgm: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
  },
  status: {S: '02: CM作成完了'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== 素材音源リスト取得 ==
WebApp --> Lambda: 素材リスト取得
Lambda --> DynamoDB: リスト取得
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== CM結合 ==
WebApp --> Lambda: CM結合
Lambda --> S3: 該当ファイル取得(getObject)
Lambda <-- S3: ファイル取得
Lambda --> Lambda: ffmpeg 結合
Lambda --> S3: ファイルPUT(putObject)
Lambda <-- S3: レスポンス
Lambda --> DynamoDB: データ更新
note right
{
  id: {S, 'ファイル名'},
  production_type: {S, '01: 音楽系, 02: 素ナレ'},
  materials: {
    narrations: [
      {
        id: {S, 'ファイル名'},
        volume: {I, 'ボリューム値'},
      }
    ],
    start_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    end_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    bgm: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
  },
  status: {S: '01: CM作成中'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== CM確定 ==
WebApp --> Lambda: CM確定
Lambda --> DynamoDB: データ更新
note right
{
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  seconds: {I, '秒数'},
  start_date: {S, '2014-10-10T13:50:40+09:00'},
  end_date: {S, '9999-12-31T23:59:59+09:00'},
  industry: {S: '業種名'},
  scene: {S: 'シーン名'},
  status: {S: '01: CM作成中'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
Lambda --> SQS: キューメッセージ送信
WebApp <-- Lambda: レスポンス

== CM音源加工（バックグラウンド） ==
Lambda <-- SQS: キューメッセージ受信
Lambda --> S3: 該当ファイル取得(getObject)
Lambda <-- S3: ファイル取得
Lambda --> Lambda: ffmpeg 音源加工
Lambda --> S3: ファイルPUT(putObject)
Lambda <-- S3: レスポンス
Lambda --> DynamoDB: データ更新
note right
{
  id: {S, 'ファイル名'},
  seconds: {I, '秒数'},
  status: {S: '02: CM作成完了'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス

== CM削除 （※センターアップロード済みの場合は、センター削除も実施）==
WebApp --> Lambda: CMデータ取得
Lambda --> DynamoDB: データ取得
note right
{
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  seconds: {I, '秒数'},
  start_date: {S, '2014-10-10T13:50:40+09:00'},
  end_date: {S, '9999-12-31T23:59:59+09:00'},
  production_type: {S, '01: 音楽系, 02: 素ナレ'},
  industry: {S: '業種名'},
  scene: {S: 'シーン名'},
  materials: {
    narrations: [
      {
        id: {S, 'ファイル名'},
        volume: {I, 'ボリューム値'},
      }
    ],
    start_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    end_chime: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
    bgm: {
      id: {S, 'ファイル名'},
      volume: {I, 'ボリューム値'},
    },
  },
  status: {S: '02: CM作成完了'}
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス
WebApp --> Lambda: CM削除
Lambda --> S3: CM削除
Lambda <-- S3: レスポンス
Lambda --> DynamoDB: データ更新
Lambda --> DynamoDB: データ更新
note right
{
  id: {S, 'ファイル名'},
  end_date: {S, '9999-12-31T23:59:59+09:00'},
  status: {S: '00: CM削除'},
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

@enduml