@startuml s3-3

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
skinparam ParticipantPadding 50
autonumber

title ** 3-3 音声録音 **

== オリジナル一覧取得 ==
WebApp --> Lambda: リスト取得
Lambda --> S3: リスト取得(listObjectsV2)
Lambda <-- S3: レスポンス
WebApp <-- Lambda: レスポンス
WebApp --> WebApp: ソート（更新日・名称）

== 音声録音作成 ==
WebApp --> WebApp: 音声録音
WebApp --> Lambda: 音声録音アップロードURL取得
Lambda --> S3: signed url 取得(getSignedUrl)
Lambda <-- S3: signed url
WebApp <-- Lambda: signed url
WebApp --> S3: 音声録音データPUT
WebApp <-- S3: レスポンス

@enduml