@startuml s3-4

participant WebApp order 1
participant Lambda order 2
participant DynamoDB order 3
participant S3 order 4
participant TTS order 5
skinparam ParticipantPadding 50
autonumber

title ** TTS作成・削除 **

== TTSリスト取得 ==
WebApp --> Lambda: リスト取得
Lambda --> DynamoDB: リスト取得
note right
{
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  start_date: {S, '2014-10-10T13:50:40+09:00'},
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス
WebApp --> WebApp: ソート（作成日・名称）

== TTSテンプレート選択 ==
WebApp --> Lambda: TTSテンプレートリスト取得
Lambda --> DynamoDB: リスト取得
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス
WebApp --> WebApp: 店名、開店時間入力

== TTS録音作成 ==
WebApp --> Lambda: TTS作成
Lambda --> TTS: TTS
Lambda <-- TTS: wav/ogg/mp3 レスポンス
Lambda --> S3: 音声録音データPUT
Lambda <-- S3: レスポンス
Lambda --> DynamoDB: データ更新
note right
{
  id: {S, 'ファイル名'},
  title: {S, 'タイトル名'},
  description: {S, '説明文'},
  start_date: {S, '2014-10-10T13:50:40+09:00'},
  timestamp: {S, '2014-10-10T13:50:40+09:00'}
}
end note
Lambda <-- DynamoDB: レスポンス
WebApp <-- Lambda: レスポンス

== CM作成へ遷移 ==

@enduml