@startuml u-messe version beta

left to right direction
rectangle "U-Messe" {
  usecase "音声録音" as u1
  usecase "TTS録音" as u2
  usecase "ストレージ" as u3
}
rectangle "外部デバイス" {
  usecase "マイク" as d1
}
rectangle "TTS" {
  usecase "TTS" as t1
}

title ** 音源作成 **
user --> u1
user --> u2
user .> d1
d1 -- u1
u1 ..> u3: 音源格納
u2 <-> t1
u2 <.. u3: テキストテンプレート取得
u2 ..> u3: 音源格納

@enduml