@startuml u-messe version beta

left to right direction
rectangle "U-Messe" {
  usecase "CM一覧" as u1
  usecase "CM作成" as u2
  usecase "CM作成履歴" as u3
  usecase "ストレージ" as u4
}

title ** CM作成 **
user --> u1
user --> u2
u1 <.. u3
u2 <.. u4

@enduml