@startuml u-messe version beta

left to right direction
rectangle "U-Messe" {
  usecase "CM一覧" as u1
  usecase "視聴" as u2
  usecase "アップロード" as u3
  usecase "ダウンロード" as u4
  usecase "再生" as u5
  usecase "ストレージ" as u6
}
rectangle "ES・センター" {
  usecase "音圧調整・CM編成" as c1
}

title ** CM出力 **
user --> u1
user --> u2
user --> u5
u1 --> u3
u3 --> c1
u4 <-- c1
u6 <. u4
u2 <.. u6
u5 <.. u6

@enduml