/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body8
 */
export interface Body8 {
    /**
     * 
     * @type {string}
     * @memberof Body8
     */
    filename?: any;
    /**
     * 
     * @type {string}
     * @memberof Body8
     */
    recordedFile?: any;
}
