/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Body9
 */
export interface Body9 {
    /**
     * 
     * @type {string}
     * @memberof Body9
     */
    text?: any;
    /**
     * 
     * @type {string}
     * @memberof Body9
     */
    speaker?: any;
    /**
     * 
     * @type {string}
     * @memberof Body9
     */
    pitch?: any;
    /**
     * 
     * @type {string}
     * @memberof Body9
     */
    speed?: any;
}
