/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CmItem
 */
export interface CmItem {
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof CmItem
     */
    seconds?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    startDate?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    endDate?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    productionType?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    industry?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    scene?: any;
    /**
     * 
     * @type {CmMaterialListItem}
     * @memberof CmItem
     */
    materials?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    status?: any;
    /**
     * 
     * @type {string}
     * @memberof CmItem
     */
    timestamp?: any;
}
