/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CmListItemInner
 */
export interface CmListItemInner {
    /**
     * シーンCD
     * @type {string}
     * @memberof CmListItemInner
     */
    sceneCd?: any;
    /**
     * シーン名
     * @type {string}
     * @memberof CmListItemInner
     */
    sceneName?: any;
    /**
     * 
     * @type {Array&lt;CmItem&gt;}
     * @memberof CmListItemInner
     */
    details?: any;
}
