/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CmMaterialListItem
 */
export interface CmMaterialListItem {
    /**
     * 
     * @type {Array&lt;CmMaterialListItemNarrations&gt;}
     * @memberof CmMaterialListItem
     */
    narrations?: any;
    /**
     * 
     * @type {CmMaterialListItemStartChime}
     * @memberof CmMaterialListItem
     */
    startChime?: any;
    /**
     * 
     * @type {CmMaterialListItemEndChime}
     * @memberof CmMaterialListItem
     */
    endChime?: any;
    /**
     * 
     * @type {CmMaterialListItemBgm}
     * @memberof CmMaterialListItem
     */
    bgm?: any;
}
