/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateCmItem
 */
export interface CreateCmItem {
    /**
     * CM ID
     * @type {string}
     * @memberof CreateCmItem
     */
    id?: any;
    /**
     * カテゴリー
     * @type {string}
     * @memberof CreateCmItem
     */
    category?: any;
    /**
     * 秒数
     * @type {number}
     * @memberof CreateCmItem
     */
    seconds?: any;
    /**
     * CM区分(音楽系:BGMあり, 素ナレ:BGMなし)
     * @type {string}
     * @memberof CreateCmItem
     */
    productionType?: any;
    /**
     * 
     * @type {Array&lt;CmMaterialListItem&gt;}
     * @memberof CreateCmItem
     */
    materials?: any;
    /**
     * CMステータス
     * @type {string}
     * @memberof CreateCmItem
     */
    status?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateCmItem
     */
    timestamp?: any;
}
