/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalMetaItem
 */
export interface ExternalMetaItem {
    /**
     * データ処理区分
     * @type {string}
     * @memberof ExternalMetaItem
     */
    dataProcessType?: any;
    /**
     * CM ID
     * @type {string}
     * @memberof ExternalMetaItem
     */
    cmId?: any;
    /**
     * 音源URL
     * @type {string}
     * @memberof ExternalMetaItem
     */
    url?: any;
    /**
     * CM名
     * @type {string}
     * @memberof ExternalMetaItem
     */
    cmName?: any;
    /**
     * CM説明
     * @type {string}
     * @memberof ExternalMetaItem
     */
    description?: any;
    /**
     * CMコメント原稿
     * @type {string}
     * @memberof ExternalMetaItem
     */
    cmCommentManuscript?: any;
    /**
     * 放送開始日時
     * @type {string}
     * @memberof ExternalMetaItem
     */
    startDatetime?: any;
    /**
     * 放送終了日時
     * @type {string}
     * @memberof ExternalMetaItem
     */
    endDatetime?: any;
    /**
     * 制作種別
     * @type {string}
     * @memberof ExternalMetaItem
     */
    productionType?: any;
    /**
     * ファイル名
     * @type {string}
     * @memberof ExternalMetaItem
     */
    fileName?: any;
    /**
     * 尺時間
     * @type {number}
     * @memberof ExternalMetaItem
     */
    contentTime?: any;
    /**
     * シーンCD
     * @type {string}
     * @memberof ExternalMetaItem
     */
    sceneCd?: any;
}
