/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalItem
 */
export interface ExternalItem {
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    dataProcessType?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    uMesseCmId?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    cmName?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    cmCommentManuscript?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    startDatetime?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    endDatetime?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    productionType?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    fileName?: any;
    /**
     * 
     * @type {number}
     * @memberof ExternalItem
     */
    contentTime?: any;
    /**
     * 
     * @type {number}
     * @memberof ExternalItem
     */
    fileSize?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    sceneCd?: any;
}
