/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalItem
 */
export interface ExternalItem {
    /**
     * 
     * @type {string}
     * @memberof ExternalItem
     */
    unisCustomerCd?: any;
    /**
     * 
     * @type {Array&lt;ExternalItem&gt;}
     * @memberof ExternalItem
     */
    cmMetas?: any;
}
