/* tslint:disable */
/* eslint-disable */
/**
 * U-Messe API
 * U-Messe API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RecordingItem
 */
export interface RecordingItem {
    /**
     * 
     * @type {number}
     * @memberof RecordingItem
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingItem
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingItem
     */
    detail?: any;
}
