/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RecordingItem
 */
export interface RecordingItem {
    /**
     * 録音音声ID
     * @type {string}
     * @memberof RecordingItem
     */
    id?: any;
    /**
     * タイトル名
     * @type {string}
     * @memberof RecordingItem
     */
    title?: any;
    /**
     * 説明文
     * @type {string}
     * @memberof RecordingItem
     */
    description?: any;
    /**
     * 掲載開始日
     * @type {string}
     * @memberof RecordingItem
     */
    startDate?: any;
    /**
     * 
     * @type {string}
     * @memberof RecordingItem
     */
    timestamp?: any;
}
