/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TemplateItemDetails
 */
export interface TemplateItemDetails {
    /**
     * 
     * @type {string}
     * @memberof TemplateItemDetails
     */
    text?: any;
    /**
     * ナレーションID
     * @type {string}
     * @memberof TemplateItemDetails
     */
    id?: any;
    /**
     * カテゴリー
     * @type {string}
     * @memberof TemplateItemDetails
     */
    category?: any;
    /**
     * 
     * @type {string}
     * @memberof TemplateItemDetails
     */
    lang?: any;
}
