/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TemplateItem
 */
export interface TemplateItem {
    /**
     * TTSテンプレートID
     * @type {string}
     * @memberof TemplateItem
     */
    id?: any;
    /**
     * カテゴリー
     * @type {string}
     * @memberof TemplateItem
     */
    category?: any;
    /**
     * タイトル
     * @type {string}
     * @memberof TemplateItem
     */
    title?: any;
    /**
     * 説明文
     * @type {string}
     * @memberof TemplateItem
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof TemplateItem
     */
    manuscript?: any;
    /**
     * 
     * @type {Array&lt;TemplateItemDetails&gt;}
     * @memberof TemplateItem
     */
    details?: any;
    /**
     * 
     * @type {Array&lt;IndustryItem&gt;}
     * @memberof TemplateItem
     */
    industry?: any;
    /**
     * 
     * @type {Array&lt;SceneItem&gt;}
     * @memberof TemplateItem
     */
    scene?: any;
    /**
     * 
     * @type {string}
     * @memberof TemplateItem
     */
    timestamp?: any;
}
