/* tslint:disable */
/* eslint-disable */
/**
 * U MESSE API
 * U MESSE API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TtsItem
 */
export interface TtsItem {
    /**
     * 合成音声ID
     * @type {string}
     * @memberof TtsItem
     */
    id?: any;
    /**
     * カテゴリー
     * @type {string}
     * @memberof TtsItem
     */
    category?: any;
    /**
     * タイトル名
     * @type {string}
     * @memberof TtsItem
     */
    title?: any;
    /**
     * 説明文
     * @type {string}
     * @memberof TtsItem
     */
    description?: any;
    /**
     * 原稿
     * @type {string}
     * @memberof TtsItem
     */
    manuscript?: any;
    /**
     * 秒数
     * @type {number}
     * @memberof TtsItem
     */
    seconds?: any;
    /**
     * 掲載開始日
     * @type {string}
     * @memberof TtsItem
     */
    startDate?: any;
    /**
     * 
     * @type {string}
     * @memberof TtsItem
     */
    timestamp?: any;
}
