openapi: 3.0.0
servers:
  - url: /api
info:
  description: U MESSE API
  version: 0.0.1
  title: U MESSE API
paths:
  /ping:
    get:
      tags:
        - ping
      summary: ping
      responses:
        default:
          description: successful response
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "ok"

  /auth:
    post:
      tags:
        - auth
      summary: 端末認証
      requestBody:
        content: 
          application/json:
            schema: 
              type: object
              properties:
                unis_customer_cd:
                  type: string
      responses:
        '200':
          description: 端末認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'

  /user:
    get:
      tags:
        - user
      summary: User情報取得
      responses:
        '200':
          description: User情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /user/cm:
    get:
      tags:
        - cm
      summary: CMリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CmItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - cm
      summary: CM新規結合
      description: ''
      operationId: ''
      requestBody:
        content: 
          application/json:
            schema: 
              type: object
              properties:
                narration:
                  type: array
                  items:
                    type: object
                    properties:
                      narrationId:
                        type: string
                      volume:
                        type: integer
                        format: int64
                startChime:
                  type: object
                  properties:
                    startChimeId:
                      type: string
                    volume:
                      type: integer
                      format: int64
                endChime:
                  type: object
                  properties:
                    endChimeId:
                      type: string
                    volume:
                      type: integer
                      format: int64
                bgm:
                  type: object
                  properties:
                    bgmId:
                      type: string
                    volume:
                      type: integer
                      format: int64
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmItem'
        default:
          description: Default error sample response

  '/user/cm/{cmId}':
    get:
      tags:
        - cm
      summary: CM情報取得
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/CmId'
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CmItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - cm
      summary: CM情報更新
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/CmId'
      requestBody:
        content: 
          application/json:
            schema: 
              type: object
              properties:
                title:
                  type: string
                  example: 'タイトル'
                description:
                  type: string
                  example: '説明文'
                seconds:
                  type: integer
                  format: int64
                startDate:
                  type: string
                  format: date-time
                endDate:
                  type: string
                  format: date-time
                  example: '掲載終了日時（固定）'
                shear:
                  type: boolean
                  example: false
                center:
                  type: boolean
                  example: true
      responses:
        default:
          description: Default response
    delete:
      tags:
        - cm
      summary: CM情報削除
      description: ''
      operationId: ''
      parameters:
        - name: cmId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default error sample response

  '/center/{cmId}':
    post:
      tags:
        - center
      summary: CMセンター連携追加
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/CmId'
      requestBody:
        content: 
          application/json:
            schema: 
              type: object
              properties:
                title:
                  type: string
                  example: 'タイトル'
                description:
                  type: string
                  example: '説明文'
                startDate:
                  type: string
                  format: date-time
                endDate:
                  type: string
                  format: date-time
                  example: '掲載終了日時（固定）'
      responses:
        default:
          description: Default response
    delete:
      tags:
        - center
      summary: CMセンター連携削除
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/CmId'
      responses:
        default:
          description: Default error sample response

  /center/download:
    get:
      tags:
        - center
      summary: センターCM連携（センター専用）
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CenterItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  '/center/download/{cmId}':
    post:
      tags:
        - center
      summary: センターCM連携完了（センター専用）
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/CmId'
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CenterItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /share:
    get:
      tags:
        - share
      summary: CM共有リスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CmItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  '/share/{cmId}':
    post:
      tags:
        - share
      summary: CM共有追加
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/CmId'
      responses:
        default:
          description: Default response
    delete:
      tags:
        - share
      summary: CM共有削除
      description: ''
      operationId: ''
      parameters:
        - name: cmId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default error sample response

  /user/recording:
    get:
      tags:
        - recording
      summary: 録音データリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RecordingItem'
    post:
      tags:
        - recording
      summary: 新規録音データ
      description: ''
      operationId: ''
      responses:
        '200':
          description: successful
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties:
                filename:
                  type: string
                recordedFile:
                  type: string
                  format: binary

  '/user/recording/{recordingId}':
    get:
      tags:
        - recording
      summary: 録音データ取得
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/RecordingId'
      responses:
        default:
          description: Default response
    post:
      tags:
        - recording
      summary: 録音データ更新（メタデータのみ）
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/RecordingId'
      responses:
        '200':
          description: successful
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties:
                filename:
                  type: string
                recordedFile:
                  type: string
                  format: binary
    delete:
      tags:
        - recording
      summary: 録音データ削除
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/RecordingId'
      responses:
        default:
          description: Default response

  /user/tts:
    get:
      tags:
        - tts
      summary: TTSデータリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TtsItem'
    post:
      tags:
        - tts
      summary: 新規録音データ
      description: ''
      operationId: ''
      responses:
        '200':
          description: successful
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties:
                filename:
                  type: string
                recordedFile:
                  type: string
                  format: binary

  '/user/tts/{ttsId}':
    get:
      tags:
        - tts
      summary: TTSデータ取得
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/TtsId'
      responses:
        default:
          description: Default response
    post:
      tags:
        - tts
      summary: TTSデータ更新（メタデータのみ）
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/TtsId'
      responses:
        '200':
          description: successful
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties:
                filename:
                  type: string
                recordedFile:
                  type: string
                  format: binary
    delete:
      tags:
        - tts
      summary: TTSデータ削除
      description: ''
      operationId: ''
      parameters:
        - $ref: '#/components/parameters/TtsId'
      responses:
        default:
          description: Default response

  /bgm:
    get:
      tags:
        - resources
      summary: BGM
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BgmItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /narration:
    get:
      tags:
        - resources
      summary: ナレーション
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/NarrationItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /chime:
    get:
      tags:
        - resources
      summary: Open/Endチャイム
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChimeItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tts:
    get:
      tags:
        - resources
      summary: TTSテンプレート一覧
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                    example: "???"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TtsItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /signedUrl:
    get:
      tags:
        - s3
      summary: S3オブジェクトの署名付きURLの取得
      description: '試聴再生、録音音声アップロード'
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  url:
                    type: string
                    example: "https://filesamples.com/samples/audio/aac/sample1.aac"
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  parameters:
    CmId:
      name: cmId
      in: path
      description: ID of cm to return
      required: true
      schema:
        type: string
        format: string
    RecordingId:
      name: recordingId
      in: path
      description: ID of recording to return
      required: true
      schema:
        type: string
        format: string
    TtsId:
      name: ttsId
      in: path
      description: ID of tts to return
      required: true
      schema:
        type: string
        format: string
  schemas:
    Auth:
      properties:
        token:
          type: string
          example: '1234567890'
    User:
      properties:
        unisCustomerCd:
          type: string
          example: 1234567890
        customerName:
          type: string
          example: "Meguro Cafe"
        customerGroupCd:
          type: string
          example: 1234567890
        customerGroupName:
          type: string
          example: "USEN"
    CmItem:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: "cm name"
        detail:
          type: string
          example: "cm detail"
    BgmItem:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: "bgm name"
        detail:
          type: string
          example: "bgm detail"
    NarrationItem:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: "narration name"
        detail:
          type: string
          example: "narration detail"
    ChimeItem:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: "chime name"
        detail:
          type: string
          example: "chime detail"
    RecordingItem:
      properties:
        id:
          type: integer
          example: 1234
        title:
          type: string
          example: "recording title"
        detail:
          type: string
          example: "recording detail"
    TtsItem:
      properties:
        id:
          type: integer
          example: 1234
        title:
          type: string
          example: "tts title"
        detail:
          type: string
          example: "tts detail"
    CenterItem:
      properties:
        id:
          type: integer
          example: 1234
        title:
          type: string
          example: "center title"
        detail:
          type: string
          example: "center detail"
    Error:
      description: Error
      type: object
      properties:
        status:
          type: string
          example: "status?"
        code:
          type: string
          example: "erorr code"
        message:
          type: string
          example: "error message"
        detail:
          type: string
          example: "error detail"
