openapi: 3.0.0
servers:
  - url: /api
info:
  description: U-Messe API
  version: 0.0.1
  title: U-Messe API
paths:
  /ping:
    get:
      tags:
        - ping
      summary: ping
      responses:
        default:
          description: successful response
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "ok"
  /auth:
    post:
      tags:
        - auth
      summary: 端末認証
      requestBody:
        content: 
          application/json:
            schema: 
              type: object
              properties:
                unis_customer_cd:
                  type: string
      responses:
        '200':
          description: 端末認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
  /user:
    get:
      tags:
        - user
      summary: User情報取得
      responses:
        '200':
          description: User情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    # post:
    #   tags:
    #     - user
    #   summary: User情報更新
    #   responses:
    #     '200':
    #       description: ok
  # /user/cm:
  #   get:
  #     tags:
  #       - user
  #     summary: UserのCM
  #     responses:
  #       '200':
  #         description: UserのCM
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/CMItem'
  /user/cm:
    get:
      tags:
        - cm
      summary: CMリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CMItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - cm
      summary: CM新規追加
      description: ''
      operationId: ''
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CMItem'
        default:
          description: Default error sample response
  '/cm/{cmId}':
    post:
      tags:
        - cm
      summary: CM情報更新
      description: ''
      operationId: ''
      parameters:
        - name: cmId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default response
    delete:
      tags:
        - cm
      summary: cm 削除
      description: ''
      operationId: ''
      parameters:
        - name: cmId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default error sample response
  /user/recording:
    get:
      tags:
        - recording
      summary: 録音データリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RecordingItem'
    post:
      tags:
        - recording
      summary: 新規録音データ
      description: ''
      operationId: ''
      responses:
        '200':
          description: successful
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties:
                filename:
                  type: string
                recordedFile:
                  type: string
                  format: binary

  '/user/recording/{recordingId}':
    get:
      tags:
        - recording
      summary: 録音データ取得
      description: ''
      operationId: ''
      parameters:
        - name: recordingId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default response
    delete:
      tags:
        - recording
      summary: 録音データ削除
      description: ''
      operationId: ''
      parameters:
        - name: recordingId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default response
  /user/tts:
    get:
      tags:
        - tts
      summary: TTSデータリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TtsItem'
    post:
      tags:
        - tts
      summary: 新規録音データ
      description: ''
      operationId: ''
      responses:
        '200':
          description: successful
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              type: object
              properties:
                filename:
                  type: string
                recordedFile:
                  type: string
                  format: binary
  '/user/tts/{ttsId}':
    get:
      tags:
        - tts
      summary: TTSデータ取得
      description: ''
      operationId: ''
      parameters:
        - name: ttsId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default response
    delete:
      tags:
        - tts
      summary: TTSデータ削除
      description: ''
      operationId: ''
      parameters:
        - name: ttsId
          in: path
          description: ID of cm to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: Default response
  /bgm:
    get:
      tags:
        - resources
      summary: BGM
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BGMItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /narration:
    get:
      tags:
        - resources
      summary: ナレーションリスト取得
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrationListItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/narration/{sceneId}':
    get:
      tags:
        - resources
      summary: ナレーション取得
      description: ''
      operationId: ''
      parameters:
        - name: sceneId
          in: path
          description: ID of narration to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NarrationSceneListItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /chime:
    get:
      tags:
        - resources
      summary: Open/Endチャイム
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChimeItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tts:
    get:
      tags:
        - resources
      summary: TTSテンプレート一覧
      description: ''
      operationId: ''
      responses:
        '200':
          description: The response
          content:
            application/json:
              schema:
                properties:
                  value:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TtsItem'
        '400':
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Auth:
      properties:
        token:
          type: string
          example: '1234567890'
    User:
      properties:
        id:
          type: integer
          example: 1234
        name:
          type: string
          example: "Meguro Cafe"
    CMItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
    BGMItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
    NarrationListItem:
      type: array
      items:
        $ref: '#/components/schemas/IndustryItem'
      example: 
        - id: 1
          name: "業種名1"
          scenes:
            - id: 11
              name: "シーン名11"
            - id: 12
              name: "シーン名12"
            - id: 13
              name: "シーン名13"
        - id: 2
          name: "業種名2"
          scenes:
            - id: 21
              name: "シーン名21"
            - id: 22
              name: "シーン名22"
            - id: 23
              name: "シーン名23"
        - id: 3
          name: "業種名3"
          scenes:
            - id: 31
              name: "シーン名31"
            - id: 32
              name: "シーン名32"
            - id: 33
              name: "シーン名33"
    IndustryItem:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: '業種名'
        scenes:
          type: array
          items:
            $ref: '#/components/schemas/SceneItem'
    SceneItem:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'シーン名'
    NarrationSceneListItem:
      type: array
      items:
        $ref: '#/components/schemas/NarrationItem'
      example: 
        - id: 1
          name: '18時30分閉店'
          detail: '放送開始日2020年10月15日 有効期限2020年10月20日'
          manuscript: '本日はご来店いただきましてありがとうございます。当店は18時30分閉店です'
          second: 10
          url: 'https://example.com'
        - id: 2
          name: 'アルバイト募集'
          detail: '放送開始日2020年10月15日 有効期限2020年10月20日'
          manuscript: '当店ではアルバイトを募集しております。なんたらかんたら'
          second: 20
          url: 'https://example.com'
        - id: 3
          name: 'チャイルドチェア'
          detail: '放送開始日2020年10月15日 有効期限2020年10月20日'
          manuscript: '本日はご来店いただきましてありがとうございます。なんたらかんたら'
          second: 30
          url: 'https://example.com'
        - id: 4
          name: 'デリバリー'
          detail: '放送開始日2020年10月15日 有効期限2020年10月20日'
          manuscript: '本日はご来店いただきましてありがとうございます。なんたらかんたら'
          second: 40
          url: 'https://example.com'
    NarrationItem:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: '18時30分閉店'
        detail:
          type: string
          example: '放送開始日2020年10月15日 有効期限2020年10月20日'
        manuscript:
          type: string
          example: '本日はご来店いただきましてありがとうございます。当店は18時30分閉店です'
        url:
          type: string
          description: '試聴URL'
          example: 'https://example.com'
        second:
          type: integer
          example: 30
    ChimeItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
    RecordingItem:
      properties:
        id:
          type: integer
        title:
          type: string
        detail:
          type: string
        
    Error:
      description: Error
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string
