openapi: 3.0.0
servers:
  - url: /api
info:
  description: U-Messe API
  version: 0.0.1
  title: U-Messe API
paths:
  /health:
    get:
      tags:
        - health
      summary: health check
      description: health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                ok:
                  value: '{"message":"ok"}'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /getSignedUrl:
    post:
      tags:
        - getSignedUrl
      summary: 署名付きURL取得
      description: S3から署名付きURLを取得する
      parameters:
        - name: params
          in: query
          schema:
            type: object
            required:
              - bucket
            properties:
              bucket:
                type: string
                example: UMesseContents
              key:
                type: string
                example: ナレーション/NA_001.mp3
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /list:
    post:
      tags:
        - list
      summary: ファイルリスト取得
      description: S3からファイルリストを取得する
      parameters:
        - name: params
          in: query
          schema:
            type: object
            required:
              - bucket
            properties:
              bucket:
                type: string
                example: UMesseContents
              key:
                type: string
                example: BGM
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /mix:
    post:
      tags:
        - mix
      summary: 音源結合
      description: 音源結合
      parameters:
        - name: params
          in: query
          schema:
            type: object
            required:
              - bucket
            properties:
              bucket:
                type: string
                example: UMesseContents
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /listTables:
    post:
      tags:
        - listTables
      summary: テーブル取得
      description: DynamoDbからテーブルを取得する
      parameters:
        - name: params
          in: query
          schema:
            type: object
            required:
              - table
            properties:
              table:
                type: string
                example: UMesseUsers
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /getItem:
    post:
      tags:
        - getItem
      summary: データ取得
      description: DynamoDbからデータを取得する
      parameters:
        - name: params
          in: query
          schema:
            type: object
            required:
              - table
            properties:
              table:
                type: string
                example: UMesseUsers
              key:
                type: string
                example: USER000001
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '500':
          description: Internal server error
